<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_GiftCard
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/** @var \Bss\Giftcard\Pricing\Render\WishlistConfigured $block */
/** @var \Bss\Giftcard\Pricing\Price\ConfiguredPrice $priceModel */

$priceModel = $block->getPrice();
$priceModel->setItem($block->getData('item'));
?>
<p><?= /* @noEscape */ $priceModel->getGiftCardPrice() ?></p>
