<?php
/**
 * @var $block \Mirasvit\Brand\Block\BrandList
 */
?>
<?php
$collection = $block->getBrandsByLetters();
?>
<div class="mst-brand__brand-list">

    <div class="toolbar">
        <a href="#" class="js-brand-letter _active" data-letter=""><?= $block->escapeHtml(__('All brands')) ?></a>

        <div class="letters">
            <?php foreach ($collection as $letter => $brands): ?>
                <a href="#" class="js-brand-letter" data-letter="<?= $block->escapeHtmlAttr($letter) ?>">
                    <?= $block->escapeHtml($letter) ?>
                </a>
            <?php endforeach; ?>
        </div>
    </div>

    <?php foreach ($collection as $letter => $brands): ?>
        <div class="letter-row js-brand-row" data-letter="<?= $block->escapeHtmlAttr($letter) ?>">
            <div class="letter"><?= $block->escapeHtml($letter) ?></div>
            <ul>
                <?php /** @var \Mirasvit\Brand\Api\Data\BrandInterface $brand */ ?>
                <?php foreach ($brands as $label => $brand): ?>
                    <li>
                        <a href="<?= $block->escapeUrl($brand->getUrl()) ?>">
                            <?php if ($block->canShowImage($brand)): ?>
                                <div class="logo-wrapper">
                                    <img alt="<?= $block->escapeHtmlAttr($label) ?>" src="<?= $block->escapeUrl($brand->getImage()) ?>">
                                </div>
                            <?php endif; ?>

                            <div class="m__all_brand_label"><?= $block->escapeHtml($label) ?></div>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endforeach; ?>
</div>
<script type="text/x-magento-init">
{
    ".js-brand-letter": {
        "Mirasvit_Brand/js/brand-list": {}
    }
}
</script>
