<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

?>
<div class="block block-customer-forget">
    <div class="block-title">
        <strong id="block-customer-forget-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('RETRIEVE YOUR PASSWORD HERE') ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-forget-heading">
        <form class="form password forget"
              action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>"
              method="post"
              id="form-validate"
              data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey')?>
            <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                <div class="field note"><?php /* @escapeNotVerified */ echo __('Please enter your email address below. You will receive a link to reset your password.'); ?></div>
                <div class="field email required">
                    <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email Address') ?></span></label>
                    <div class="control">
                        <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="secondary">
                    <a class="action back" href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('BACK TO LOGIN') ?></span></a>
                </div>
                <div class="primary">
                    <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('SUBMIT') ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>