<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Cookie\Block\Html\Notices $block */
?>
<?php if ($this->helper(\Magento\Cookie\Helper\Cookie::class)->isCookieRestrictionModeEnabled()): ?>
    <div role="alertdialog"
         tabindex="-1"
         class="message global cookie"
         id="notice-cookie-block"
         style="display: none;">
        <div role="document" class="content" tabindex="0">
            <p>
                <span><?= $block->escapeHtml(__('هذا الموقع يستعمل ملفات تعريف الارتباط ليتذكر ضوابط الاستخدام وليمنحك تجربة افضل في التصفح ')) ?></span>
                <br/>
                <button id="btn-cookie-allow" class="action allow primary">
                    <span><?= $block->escapeHtml(__('موافق')) ?></span>
                </button>             
                <span>
                    <?= $block->escapeHtml(__('للمزيد من المعلومات يمكنك زيارة صفحة'));?><?= $block->escapeHtml(__('<a href="%1"> سياسة الخصوصية </a>', $this->getUrl().'privacy-policy?___store=ar&___from_store=default'), ['a']) ?></span>
            </p>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "#notice-cookie-block": {
                "cookieNotices": {
                    "cookieAllowButtonSelector": "#btn-cookie-allow",
                    "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                    "cookieValue": <?= /* @noEscape */ $this->helper(\Magento\Cookie\Helper\Cookie::class)->getAcceptedSaveCookiesWebsiteIds() ?>,
                    "cookieLifetime": <?= /* @noEscape */ $this->helper(\Magento\Cookie\Helper\Cookie::class)->getCookieRestrictionLifetime() ?>,
                    "noCookiesUrl": "<?= $block->escapeJs($block->escapeUrl($block->getUrl('cookie/index/noCookies'))) ?>"
                }
            }
        }
    </script>
<?php endif; ?>
