<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomOptionTemplate
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2022 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile
/** @var $block \Bss\CustomOptionTemplate\Block\Adminhtml\Template\Edit\Tab\Options\Option */
$listStoreView= $block->getListStoreView();
$getListCustomerGroupArray = $block->getListCustomerGroupArray();

?>
<?php echo $block->getTemplatesHtml() ?>
<script id="custom-option-base-template" type="text/x-magento-template">
    <div class="fieldset-wrapper admin__collapsible-block-wrapper opened" id="option_<%- data.id %>">
        <div class="fieldset-wrapper-title">
            <strong
                class="admin__collapsible-title"
                data-toggle="collapse"
                data-target="#<%- data.id %>-content">
                <span id="option_<%- data.id %>_header_title"><%- data.title %></span>
            </strong>
            <div class="actions">
                <button type="button" title="<?php /* @escapeNotVerified */ echo __('Delete Custom Option'); ?>" class="action-delete" id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_delete">
                    <span><?php /* @escapeNotVerified */ echo __('Delete Custom Option'); ?></span>
                </button>
            </div>
            <div id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_move" data-role="draggable-handle" class="draggable-handle"
                 title="<?php /* @escapeNotVerified */ echo __('Sort Custom Options'); ?>"></div>
        </div>
        <div class="fieldset-wrapper-content in collapse" id="<%- data.id %>-content">
            <fieldset class="fieldset">
                <fieldset class="fieldset-alt determined-location" id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>">
                    <input id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_is_delete" name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][is_delete]" type="hidden" value=""/>
                    <input id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_previous_type" name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][previous_type]" type="hidden" value="<%- data.type %>"/>
                    <input id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_previous_group" name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][previous_group]" type="hidden" value=""/>
                    <input id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_id" name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][id]" type="hidden" value="<%- data.id %>"/>
                    <input id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_option_id" name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][option_id]" type="hidden" value="<%- data.option_id %>"/>
                    <input name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][sort_order]" type="hidden" value="<%- data.sort_order %>"/>

                    <div class="field field-option-title required">
                        <label class="label" for="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_title">
                            <?php /* @escapeNotVerified */ echo __('Option Title') ?>
                        </label>
                        <div class="control">
                            <input id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_title"
                                   name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][title]"
                                   class="required-entry input-text"
                                   type="text"
                                   value="<%- data.title %>"
                                   data-store-label="<%- data.title %>"
                                   <% if (typeof data.scopeTitleDisabled != 'undefined' && data.scopeTitleDisabled != null) { %> disabled="disabled" <% } %>
                                   >
                            <%= data.checkboxScopeTitle %>
                        </div>
                    </div>

                    <div class="field field-option-input-type required">
                        <label class="label" for="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_title">
                            <?php /* @escapeNotVerified */ echo __('Input Type') ?>
                        </label>
                        <div class="control opt-type">
                            <?php echo $block->getTypeSelectHtml() ?>
                        </div>
                    </div>

                    <div class="field field-option-req">
                        <div class="control">
                            <input id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_required" class="is-required" type="checkbox" checked="checked"/>
                            <label for="field-option-req">
                                <?php /* @escapeNotVerified */ echo __('Required')?>
                            </label>
                            <span style="display:none"><?php echo $block->getRequireSelectHtml() ?></span>
                        </div>
                    </div>
                    <div class="field field-option-req no-display">
                        <div class="control">
                            <label for="field-option-req">
                                <?php /* @escapeNotVerified */ echo __('Option ID')?>
                            </label>
                            <?php if ($block->isCompatibleDependentCO()): ?>
                                <span class="bss_dco_span" id="bss-dco-span-<%- data.id %>"><%- data.dependent_id %></span>
                                <input type="hidden" class="dependent-id parent-option-dependent-id" id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_dependent_id" name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][dependent_id]" value="<%- data.dependent_id %>" option_key="<%- data.id %>">
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php if ($block->isCompatibleAbsolutePriceQuantity()): ?>
                        <div class="field field-option-req">
                            <div class="control">
                                <input id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_coap_qty" class="bss_coap_qty" type="checkbox" checked="checked"/>
                                <label for="field-option-req">
                                    <?php /* @escapeNotVerified */ echo __('Qty')?>
                                </label>
                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][bss_coap_qty]" value="<%- data.bss_coap_qty %>">
                            </div>
                        </div>
                    <?php endif ?>
                    <div class="field field-option-req">
                        <div class="option-visible template-div-modal">
                            <div class="control">
                                <div class="add-visible-button button-show-modal" data-toggle="tooltip" data-placement="top" title="<?php /* @escapeNotVerified */ echo __('Visibility');?>"></div>
                            </div>
                            <aside role="dialog" class="modal-slide  product_form_product_form_store_title_modal" aria-labelledby="modal-title-14" aria-describedby="modal-content-14" data-role="modal" data-type="slide" tabindex="0" style="z-index: 902;">
                                <div data-role="focusable-start" tabindex="0"></div>
                                <div class="modal-inner-wrap" data-role="focusable-scope">
                                    <header class="modal-header">
                                        <h1 id="modal-title-14" class="modal-title" data-role="title"><?php /* @escapeNotVerified */ echo __('Manage Visibility');?>
                                        </h1>
                                        <button class="action-close button-close-modal" type="button">
                                            <span><?php /* @escapeNotVerified */ echo __('close');?></span>
                                        </button>
                                        <div class="page-main-actions">
                                            <div class="page-actions">
                                                <div class="page-actions-buttons">
                                                    <button class="action-primary button-close-modal"  type="button"><span><?php /* @escapeNotVerified */ echo __('Done');?></span>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </header>
                                    <div class="modal-content" data-role="content">
                                        <div class="modal-component">
                                            <div class="fieldset-wrapper _show" data-level="0">
                                                <div class="admin__fieldset-wrapper-content _hide">
                                                    <fieldset class="admin__fieldset">
                                                        <fieldset class="admin__field" data-index="group_container_0">
                                                            <legend class="admin__field-label">
                                                                <span><?php /* @escapeNotVerified */ echo __('Customer Group');?></span>
                                                            </legend>
                                                            <div class="admin__field-control admin__field-group-columns admin__control-fields">
                                                                <div class="admin__field">
                                                                    <div class="admin__field-control">
                                                                        <select multiple="" class="admin__control-multiselect visible-customer-group">
                                                                            <?php foreach ($getListCustomerGroupArray as $customerGroup) : ?>
                                                                            <option value="<?= /* @escapeNotVerified */ $customerGroup['value']?>"><?= /* @escapeNotVerified */ __($customerGroup['label']);?></option>
                                                                            <?php endforeach;?>
                                                                        </select>
                                                                    </div>
                                                                    <input type="hidden" value="<%- data.visible_for_group_customer %>"
                                                                           class="data-visible-customer" name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][visibility][customer_group]" />
                                                                </div>
                                                            </div>
                                                        </fieldset>
                                                        <fieldset class="admin__field" data-index="group_container_0">
                                                            <legend class="admin__field-label">
                                                                <span><?php /* @escapeNotVerified */ echo __('Stores');?></span>
                                                            </legend>
                                                            <div class="admin__field-control admin__field-group-columns admin__control-fields">
                                                                <div class="admin__field">
                                                                    <div class="admin__field-control _with-tooltip">
                                                                        <select multiple="" class="admin__control-multiselect visible-store-view">
                                                                            <?php foreach ($listStoreView as $store) : ?>
                                                                                <option value="<?= /* @escapeNotVerified */ $store['value']?>"><?= /* @escapeNotVerified */ __($store['label']);?></option>
                                                                            <?php endforeach;?>
                                                                        </select>
                                                                    </div>
                                                                    <input type="hidden" value="<%- data.visible_for_store_view %>"
                                                                           class="data-visible-store" name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][visibility][stores]" />
                                                                </div>
                                                            </div>
                                                        </fieldset>
                                                    </fieldset>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div data-role="focusable-end" tabindex="0"></div>
                            </aside>
                        </div>
                    </div>
                    <div class="field field-option-req">
                        <div class="option-store-title-div template-div-modal">
                            <div class="control">
                            <div class="add-store-title-button button-show-modal" data-toggle="tooltip" data-placement="top" title="<?php /* @escapeNotVerified */ echo __('Store View Titles');?>"></div>
                            </div>
                            <aside role="dialog" class="modal-slide  product_form_product_form_store_title_modal" aria-labelledby="modal-title-14" aria-describedby="modal-content-14" data-role="modal" data-type="slide" tabindex="0" style="z-index: 902;">
                                <div data-role="focusable-start" tabindex="0"></div>
                                <div class="modal-inner-wrap" data-role="focusable-scope">
                                    <header class="modal-header">
                                        <h1 id="modal-title-14" class="modal-title" data-role="title"><?php /* @escapeNotVerified */ echo __('Store View Titles');?>
                                        </h1>
                                        <button class="action-close button-close-modal" data-role="closeBtn" type="button">
                                            <span><?php /* @escapeNotVerified */ echo __('close');?></span>
                                        </button>
                                        <div class="page-main-actions">
                                            <div class="page-actions">
                                                <div class="page-actions-buttons">
                                                    <button class="action-primary button-close-modal" type="button"><span><?php /* @escapeNotVerified */ echo __('Done');?></span>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </header>
                                    <div class="modal-content" data-role="content">
                                        <div class="modal-component">
                                            <div class="fieldset-wrapper _show" data-level="0">
                                                <div class="admin__fieldset-wrapper-content _hide">
                                                    <fieldset class="admin__fieldset">
                                                        <?php foreach ($listStoreView as $storeview) : ?>
                                                        <fieldset class="admin__field" data-index="group_container_0">
                                                          <legend class="admin__field-label">
                                                                <span><?php /* @escapeNotVerified */ echo __($storeview['label']);?></span>
                                                            </legend>
                                                            <div class="admin__field-control admin__field-group-columns admin__control-fields">
                                                                <div class="admin__field">
                                                                    <div class="admin__field-control">
                                                                        <input id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_title_<?php /* @escapeNotVerified */ echo $storeview['value'] ?>" data-index="<?php echo $storeview['value'];?>" class="admin__control-text option-title-store"
                                                                               type="text" placeholder="empty to use global title" maxlength="255">
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </fieldset>
                                                        <?php endforeach;?>
                                                        <input type="hidden" value="<%- data.title_option %>" class="data-title-store" name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][title_option]" />
                                                    </fieldset>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div data-role="focusable-end" tabindex="0"></div>
                            </aside>
                        </div>
                    </div>
                    <br>
                    <?php if ($block->isCompatibleAbsolutePriceQuantity()): ?>
                        <div class="field field-option-input-type">
                            <label class="label">
                                <?php /* @escapeNotVerified */ echo __('Description Type') ?>
                            </label>
                            <div class="control">
                                <select name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][bss_description_option_type]"
                                        class="select select-product-option-bss-description-option-type" title="">
                                    <option <%- data.bss_description_option_type == 0 ? 'selected' : '' %> value="0">
                                        <?php /* @escapeNotVerified */ echo __('None') ?>
                                    </option>
                                    <option <%- data.bss_description_option_type == 1 ? 'selected' : '' %>  value="1">
                                        <?php /* @escapeNotVerified */ echo __('Tooltip') ?>
                                    </option>
                                    <option <%- data.bss_description_option_type == 2 ? 'selected' : '' %> value="2">
                                        <?php /* @escapeNotVerified */ echo __('Small text') ?>
                                    </option>
                                </select>
                            </div>
                        </div>
                        <div class="field field-option-title">
                            <label class="label" for="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_bss_description_option">
                                <?php /* @escapeNotVerified */ echo __('Short Description') ?>
                            </label>
                            <div class="control">
                                <input name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][bss_description_option]"
                                       id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_bss_description_option"
                                       class="input-text" type="text" value="<%- data.bss_description_option %>">
                            </div>
                        </div>
                    <?php endif ?>
                </fieldset>
            </fieldset>
        </div>
    </div>
</script>

<div id="import-container" style="display: none;"></div>
<?php if (!$block->isReadonly()): ?>
<div><input type="hidden" name="affect_product_custom_options" value="1"/></div>
<?php endif; ?>

<script>
require([
    "jquery",
    "Bss_CustomOptionTemplate/js/custom-options"
], function(jQuery){
    jQuery(function ($) {
        var fieldSet = $('[data-block=product-custom-options]');
        fieldSet.customOptions(<?php /* @escapeNotVerified */ echo $block->serializeJson(
            [
                'fieldId' => $block->getFieldId(),
                'productGridUrl' => $block->getProductGridUrl(),
                'formKey' => $block->getFormKey(),
                'customOptionsUrl' => $block->getCustomOptionsUrl(),
                'isReadonly' => $block->isReadonly(),
                'itemCount' => $block->getItemCount(),
                'currentProductId' => $block->getCurrentProductId(),
            ]
        )?>);
        //adding data to templates
        <?php /** @var $_value \Magento\Framework\DataObject */ ?>
        <?php foreach ($block->getOptionValues() as $_value): ?>
            fieldSet.customOptions('addOption', <?php /* @escapeNotVerified */ echo $_value->toJson() ?>);
        <?php endforeach; ?>
    });
    window.bss_list_websites_array = <?php /* @escapeNotVerified */ echo $block->getListWebsitesArray(); ?>;
    window.bss_list_customer_group_array = <?php /* @escapeNotVerified */ echo  $block->getCustomerGroupsArray();?>;
    window.bss_currency_symbol = <?php /* @escapeNotVerified */ echo  '"'.$block->getCurrencySymbol().'"';?>;
    <?php if ($block->isCompatibleDependentCO()): ?>
        window.bss_depend_option = <?php /* @escapeNotVerified */ echo json_encode($block->getBssDependOptions(), JSON_FORCE_OBJECT) ?>;
        window.bss_depend_id = <?php /* @escapeNotVerified */ echo json_encode($block->getBssDependIds(), JSON_FORCE_OBJECT) ?>;
    <?php endif; ?>
});
</script>
<?php if ($block->isCompatibleDependentCO()): ?>
    <input type="hidden" id="cot-depend-last-increment-id" value="<?= $block->getLastIncrementId() ?>">
<?php endif; ?>
<script id="custom-option-row-tier-price" type="text/x-magento-template">
    <tr>
        <td class="col-websites">
            <select class="required-entry inputValue admin__control-select" data-check-type="website_id" name="<%- data.inputName %>[<%- data.index %>][website_id]" id="option_tier_price_row_<%- data.inputName %><%- data.index %>_website">
                </select></td>
        <td class="col-customer-group"><select class=" custgroup required-entry inputValue admin__control-select" data-check-type="cust_group" name="<%- data.inputName %>[<%- data.index %>][cust_group]" id="option_tier_price_row_<%- data.inputName %><%- data.index %>_cust_group">
            </select></td>
        <td class="col-qty">
            <input class="qty required-entry validate-greater-than-zero validate-number inputValue admin__control-text" data-check-type="price_qty" type="text" name="<%- data.inputName %>[<%- data.index %>][price_qty]" value="<%- data.qty %>" id="option_tier_price_row_<%- data.index %>_qty" />
            </td>
        <td class="col-price control-grouped admin__control-fields">
            <div class="admin__field-control control-grouped admin__control-fields">
                <div class="admin__field">
                    <select class=" price-type required-entry inputValue admin__control-select"  data-check-type="price-type" name="<%- data.inputName %>[<%- data.index %>][price-type]" id="option_tier_price_row_<%- data.inputName %><%- data.index %>_price_type">
                        <option value="fixed"><?php /* @escapeNotVerified */ echo  __('Fixed'); ?></option>
                        <option value="percent"><?php /* @escapeNotVerified */ echo __('Discount'); ?></option>
                        </select></div>
                <div class="admin__field">
                    <label class="admin__addon-prefix bss-abs-symbol"> <span><%- data.symbol %></span> </label>
                    <input class="required-entry bss-abs-price-input validate-greater-than-zero validate-number inputValue admin__control-text" type="text"  data-check-type="price" name="<%- data.inputName %>[<%- data.index %>][price]" value="<%- data.price %>" id="option_tier_price_row_<%- data.inputName %><%- data.index %>_price" /></div></div></td>'
        <td class="col-delete"><input type="hidden" name="<%- data.inputName %>[<%- data.index %>][delete]" class="delete" value="" id="option_tier_price_row_<%- data.inputName %><%- data.index %>_delete" />
            <button title="Delete Tier" type="button" class="action-delete option-tier-price icon-btn delete-product-option" id="option_tier_price_row_<%- data.inputName %><%- data.index %>_delete_button">
                <span><?php /* @escapeNotVerified */ echo __('Delete'); ?></span></button></td>
        </tr>
</script>
