<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var $block Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare */
?>
<a href="#"
   class="action tocompare"
   title="<?php echo $block->escapeHtml(__('أضف للمقارنة')); ?>"
   aria-label="<?php echo $block->escapeHtml(__('أضف للمقارنة')); ?>"
   data-post='<?php /* @escapeNotVerified */ echo $block->getCompareHelper()->getPostDataParams($block->getProduct()); ?>'
   role="button">
    <span><?php /* @escapeNotVerified */ echo __('أضف للمقارنة') ?></span>
</a>
