<?php
/**
 * @var $block \Mirasvit\LayeredNavigation\Block\Renderer\RatingRenderer
 * @var $escaper \Magento\Framework\Escaper
 */
$attributeCode     = $block->getAttributeCode();
$checkedItemsCount = 0;
?>
<div class="mst-nav__label mst-nav__rating" data-mst-nav-filter="<?= $block->escapeHtmlAttr($attributeCode) ?>">
    <ol class="items">
        <?php foreach ($block->getFilterItems() as $filterItem): ?>
            <?php
            $itemRating      = $filterItem->getValueString();
            $numberOfResults = $filterItem->getData('count');
            $isItemChecked   = $block->isFilterItemChecked($filterItem);
            $url             = $isItemChecked ? $filterItem->getRemoveUrl() : $filterItem->getUrl();

            if ($isItemChecked) {
                $checkedItemsCount++;
            }

            $cssClass = [
                'item',
                'mst-nav__label-item',
                $isItemChecked ? '_checked' : '',
                $isItemChecked && $block->isHighlightEnabled() ? '_highlight' : '',
            ];
            ?>

            <li class="<?= $block->escapeHtmlAttr(implode(' ', $cssClass)) ?>" data-element="filter" data-value="<?= $block->escapeHtmlAttr($filterItem->getValueString()) ?>">
                <a href="<?= $escaper->escapeUrl($url) ?>" rel="<?= $block->escapeHtmlAttr($block->getRelAttributeValue()) ?>">
                    <div class="rating-summary">
                        <div class="rating-result" title="<?= $itemRating * 20 ?>%">
                            <span style="width:<?= $block->escapeHtmlAttr($itemRating * 20) ?>%"><span><?= $block->escapeHtml($itemRating) ?></span></span>
                        </div>

                        <span><?= $block->escapeHtml(__(' & Up')) ?></span>

                        <?= /* @noEscape */ $block->getCountElement($filterItem) ?>
                    </div>
                </a>
            </li>
        <?php endforeach ?>
    </ol>
</div>
<script type="text/x-magento-init"><?= \Mirasvit\Core\Service\SerializeService::encode([
        '[data-mst-nav-filter=' . $attributeCode . ']' => [
            'Mirasvit_LayeredNavigation/js/renderer/label-renderer' => [],
            'Mirasvit_LayeredNavigation/js/helper/checked-items' => [
                'count'    => $checkedItemsCount,
                'clearUrl' => $block->getAttributeClearUrl($attributeCode)
            ],
        ],
    ]) ?></script>
