<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomOptionAbsolutePriceQuantity
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile
/* @var $block \Bss\CustomOptionAbsolutePriceQuantity\Block\Adminhtml\Render\OrderOptionTip */
?>
<?php $option = $block->getOption(); ?>
<div id="bss_options_<?php echo $option->getId() ?>"></div>
<?php if ($block->getPriceTypeData()) : ?>
    <script>
        var data = <?php echo $block->getPriceTypeData()?>;
        var isStatic = "<?php echo $block->isStaticSelectType()?>";
        var optionId = "<?php echo $option->getId()?>";
        require(['jquery', 'jquery/ui'], function($){
            $.each(data, function (k, vl) {
                if (isStatic) {
                    if ($('#options-' + optionId + '-list').find('.product-custom-option[value=' + vl + ']').attr('tip') != 1) {
                        $('#options-' + optionId + '-list').find('.product-custom-option[value=' + vl + ']')
                        .attr('tip', 1).siblings('label').append('<span class="price-notice"><?php echo $block->escapeHtml(__('(Absolute Price)')) ?></span>');
                    }
                } else {
                    if ($('#select_' + optionId).find('option[value=' + vl + ']').attr('tip') != 1) {
                        $('#select_' + optionId).find('option[value=' + vl + ']').attr('tip', 1).append('<?= $block->escapeHtml(__(' (Absolute Price)'))?>');
                    }
                }
            });
        });
    </script>
<?php endif; ?>
