<?php
/**
 * @var Bss\RewardPoint\Block\Customer\PointShowing
 */
//  @codingStandardsIgnoreFile
?>
<?php
$pointIconUrl = $block->getPointIconUrl();
if (!empty($pointIconUrl)) :
    ?>
    <style type="text/css">
        .reward-point-message:before {
            background-image: url("<?= $pointIconUrl ?>");
            background-repeat: no-repeat;
            background-size: 100%;
            display: inline-block;
            width: 20px;
            content: "";
            margin-right: 8px;
        }
        .reward-point-message {
            display: inline-flex !important;
            min-width: 22px;
            min-height: 22px;
        }
    </style>
<?php endif; ?>
<?php if($block->customerLoggedIn() && $block->isShowPointInHeader()): ?>
    <li class="reward-point-message" data-bind="scope: 'rewardPointSection'">
        <!-- ko if: rewardPointValue().rewardPoint  -->
        <span class="balance-point"
              data-bind="text: new String('<?= $block->escapeHtml(__('You have %1 points', '%1')) ?>').replace('%1', rewardPointValue().rewardPoint)">
        </span>
        <!-- /ko -->
        <!-- ko ifnot: rewardPointValue().rewardPoint  -->
        <span class="balance-point"
              data-bind="text: new String('<?= $block->escapeHtml(__('You have %1 point', '%1')) ?>').replace('%1', 0)">
        </span>
        <!-- /ko -->
    </li>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "rewardPointSection": {
                            "component": "Bss_RewardPoint/js/section/header/reward-point"
                        }
                    }
                }
            }
        }
    </script>
<?php endif; ?>
