<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomOptionAbsolutePriceQuantity
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

/**
 * Text options block
 *
 * @var $block \Bss\CustomOptionAbsolutePriceQuantity\Block\Pricing\SubtotalRender
 */
?>
<div class="coap_subtotal_template"></div>
<script type="text/x-magento-init">
    {
        ".coap_subtotal_template": {
            "coapSubtotal": {
                "finalPrice": "<?php /* @escapeNotVerified */ echo $block->getProductFinalPrice(); ?>",
                "basePrice": "<?php /* @escapeNotVerified */ echo $block->getProductBaseFinalPrice(); ?>",
                <?php if ($block->getConfigHelper()->getPriceDisplayType()) : ?>
                    "displayType": "<?= /* @escapeNotVerified */ $block->getConfigHelper()->getPriceDisplayType(); ?>",
                <?php endif; ?>
                <?php if ($block->getPricesData()) : ?>
                    "configurablePricesData": <?php /* @escapeNotVerified */ echo $block->getPricesData(); ?>,
                <?php endif; ?>
                "tierPrices": <?php /* @escapeNotVerified */ echo $block->getTierPricesData(); ?>,
                "tierPricesOption" : <?= /* @escapeNotVerified */ $block->getTierPricesOptionData(); ?>,
                "optionQtyData" : <?= /* @escapeNotVerified */ $block->getOptionQtyData(); ?>,
                "optionToolTip" : <?= /* @escapeNotVerified */ $block->getAbsToolTip(); ?>,
                "regularPrice" : <?= /* @escapeNotVerified */ $block->getRegularPrice(); ?>,
                "regularPriceTax" : <?= /* @escapeNotVerified */ $block->getRegularPriceIncl(); ?>
            }
        }
    }
</script>
