<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_MinMaxAmountOrderPerCate
 * @author     Extension Team
 * @copyright  Copyright (c) 2020-2021 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
use Bss\MinMaxAmountOrderPerCate\ViewModel\HelperViewModel;

/**
 * @var $block \Magento\Checkout\Block\Cart\Item\Renderer
 * @var $viewModel HelperViewModel
 */
?>
<?php
$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
$viewModel = $block->getData('viewModel');
$canApplyMsrp = $viewModel->isShowBeforeOrderConfirm($product) && $viewModel->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?=$block->escapeHtml(__('Item'))?>" class="col item">
            <?php if ($block->hasProductUrl()):?>
                <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else:?>
                <span class="product-item-photo">
            <?php endif;?>
            <?=$block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml()?>
            <?php if ($block->hasProductUrl()):?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()):?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>">
                            <?=$block->escapeHtml($block->getProductName())?>
                        </a>
                    <?php else: ?>
                        <?=$block->escapeHtml($block->getProductName())?>
                    <?php endif; ?>
                </strong>
                <!-- add category name -->
                    <span>
                        <?=$block->escapeHtml(__('Category name(s): ')) ?>
                        <?= /* @noEscape */ $block->getBssCategoryNames() ?>
                    </span>
                <!--  -->
                <?php if ($_options = $block->getOptionList()):?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option): ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <?= /* @noEscape */ $_formatedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?= /* @noEscape */ $_formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif; ?>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="cart item message <?= /* @noEscape */ $message['type'] ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>

        <?php if ($canApplyMsrp): ?>
            <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')); ?>">
                <span class="pricing msrp">
                    <span class="msrp notice">
                        <?= $block->escapeHtml(__('See price before order confirmation.')) ?>
                    </span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?= /* @noEscape */ ($helpLinkId); ?>"
                       data-mage-init='{"addToCart":{"helpLinkId": "#<?= /* @noEscape */ $helpLinkId;?>",
                       "productName": "<?= /* @noEscape */ $product->getName(); ?>","showAddToCart": false}}'>
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
            </td>
        <?php else: ?>
            <td class="col price" data-th="<?= $block->escapeHtml(__('Price')); ?>">
                <?= $block->getUnitPriceHtml($_item); ?>
            </td>
        <?php endif; ?>
        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')); ?>">
            <div class="field qty">
                <label class="label" for="cart-<?= /* @noEscape */  $_item->getId() ?>-qty">
                    <span><?= $block->escapeHtml(__('Qty')) ?></span>
                </label>
                <div class="control qty">
                    <input id="cart-<?= /* @noEscape */ $_item->getId() ?>-qty"
                           name="cart[<?= /* @noEscape */ $_item->getId() ?>][qty]"
                           data-cart-item-id="<?= /* @noEscape */ $_item->getSku() ?>"
                           value="<?= /* @noEscape */ $block->getQty() ?>"
                           type="number"
                           size="4"
                           title="<?= $block->escapeHtml(__('Qty')); ?>"
                           class="input-text qty"
                           maxlength="12"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/>
                </div>
            </div>
        </td>

        <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else: ?>
                <?= $block->getRowTotalHtml($_item) ?>
            <?php endif; ?>
        </td>
    </tr>
    <tr class="item-actions">
        <td colspan="100">
            <div class="actions-toolbar">
                <?= /* @noEscape */ $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>
