<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_QuoteExtension
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2023 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/**
 * @var \Bss\QuoteExtension\Block\Adminhtml\Order\View\Info $block
 */
?>

<?php if ($block->getQuoteExtemsionIncrementId()) : ?>
    <tr>
        <th><?= $block->escapeHtml(__('Related Quote')) ?></th>
        <td><a href="<?= $block->escapeHtml($block->getQuoteUrl()) ?>">
                <?= $block->escapeHtml($block->getQuoteExtemsionIncrementId()) ?>
            </a>
    </tr>
<?php endif; ?>
