<div>
<a href="/tech/virtualtryon">
    <img src="<?php echo $block->getViewFileUrl('Unveels_AddFloatingIcons::images/ai-tryon-icon.png'); ?>" 
         class="floating-icon" alt="Virtual Assistant Voice Command AI"/>
</a>
         <a href="/tech/virtualassistant">
    <img src="<?php echo $block->getViewFileUrl('Unveels_AddFloatingIcons::images/virtual-assistant-voice-command-ai.png'); ?>" 
         class="floating-icon second" alt="Virtual Assistant Voice Command"/>
</a>
</div>
