<?php
/** @var \Prince\Productattach\Block\Attachment $block */
?>
<?php if($block->isEnable()): ?>
    <?php $productId = $block->getCurrentId(); ?>
    <?php $attachments = $block->getAttachment($productId); ?>
    <?php $isSize = $block->getConfig('productattach/general/attachmentsize'); ?>
    <?php /** @var \Prince\Productattach\Model\Productattach $attachment */ ?>
    <?php foreach ($attachments as $attachment) : ?>
        <?php if ($attachment->getActive()) : ?>
            <div class="product-attachment" style="margin-bottom: 10px;">
                <?php if ($attachment->getFile() && $block->fileExists($attachment->getFile())) : ?>
                    <a href="<?php /* @noEscape */ echo $block->getAttachmentUrl($attachment->getFile()); ?>" target="_blank">
                        <div class="attachment-icon" style="padding-right: 10px;">
                            <img class="img-valign" style="vertical-align: middle; margin-bottom: 0.75em;" src="<?php /* @noEscape */ echo $block->getFileIcon($attachment->getFileExt()) ?>" style="width: 20px"/>
                            <span><?php /* @noEscape */ echo $attachment->getName(); ?></span>
                        </div>
                    </a>
                    <?php if ($isSize) : ?>
                        <?php $size = '(Size: '.$block->getFileSize($attachment->getFile()).')' ?>
                        <?php /* @noEscape */ echo __($size); ?>
                    <?php endif; ?>
                <?php elseif ($attachment->getUrl()) : ?>
                    <a href="<?php /* @noEscape */ echo $attachment->getUrl(); ?>" target="_blank" >
                        <div class="attachment-icon" style="padding-right: 10px;">
                            <img class="img-valign" style="vertical-align: middle; margin-bottom: 0.75em;"> src="<?php /* @noEscape */ echo $block->getLinkIcon(); ?>" />
                            <span><?php /* @noEscape */ echo $attachment->getName(); ?></span>
                        </div>
                    </a>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>