<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_GiftCard
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

/**
 * Gift Card product data template
 *
 * @var $block \Bss\GiftCard\Block\Product\View\Type\GiftCard
 */
?>
<?php
    $product = $block->getProduct();
?>
<?php if ($product->isSalable() && $product->getBssGiftCardExpires()): ?>
    <div id="bss-giftcard-expires">
        <span><?= __('Expires After %1 day(s)', $product->getBssGiftCardExpires())?></span>
    </div>
<?php endif; ?>
