<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="sub-footer">
<div class="contener">
<div class="subscribe-form">
<p>Sign up for Exclusive Offers &amp; Updates</p>
<div class="subscribe-div"><form class="form subscribe" action="https://jotex.jo/newsletter/subscriber/new/" method="post" novalidate="novalidate">
    <label class="hide-label" for="sub-email"></label><em class="spirit_image spirit_image_newsletter_image ">&nbsp;</em><input id="sub-email" class="sub-email spirit_image_news  " name="email" type="email" value="" placeholder="Enter your e-mail address"> <input id="sub-submit2" class="sub-btn action subscribe primary" name="subscribe" type="submit" value="Subscribe">
<?php echo $block->getBlockHtml('formkey')?>
</form></div>
</div>
<div class="social-link">
<ul>
<li><a href="https://www.facebook.com/Jotex-265095446896998/" target="_blank" rel="noopener"> <img src="https://jotex.jo/pub/media/wysiwyg/footer/fb.png" alt="Jotex Facebook" width="37" height="37"> </a></li>
<li><a href="https://www.youtube.com/channel/UC7kzbSva59Ij4U5E89qMM4g" target="_blank" rel="noopener"> <img src="https://jotex.jo/pub/media/wysiwyg/footer/youtube.jpg" alt="Jotex Youtube" width="37" height="37"> </a></li>
<li><a href="https://www.linkedin.com/company/jotex-jordan/" target="_blank" rel="noopener"> <img src="https://jotex.jo/pub/media/wysiwyg/footer/linkedin.png" alt="Jotex Linked" width="37" height="37"> </a></li>
<li><a href="https://www.instagram.com/jotex_shireentrading/" target="_blank" rel="noopener"> <img src="https://jotex.jo/pub/media/wysiwyg/footer/instegram.png" alt="Jotex instagram" width="37" height="37"> </a></li>
</ul>
</div>
</div>
</div>
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer')->toHtml();?>
<small class="copyright">
				<div class="contener">
			    <span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span>
			    <a class="sitemap" href="<?php echo $this->getUrl('sitemap');?>">Sitemap</a>
                    <div class="home spirit_image spirit_image_copy_home"></div>
			    </div>
			</small>
<script type="text/javascript">
    require(['jquery','flexslider'],function($){
      $(document).ready(function(){
      $('.flexslider').flexslider({
        animation: "slide",
        controlsContainer: $(".custom-controls-container"),
        customDirectionNav: $(".custom-navigation a"),
        start: function(slider) { $(".slidermain .slider").removeClass('loading');}
      });
    });
    
     $(document).on('mana-after-content-replaced', function(event, $containers) {
      $('.flexslider').flexslider({
        animation: "slide",
        controlsContainer: $(".custom-controls-container"),
        customDirectionNav: $(".custom-navigation a"),
        start: function(slider) { $(".slidermain .slider").removeClass('loading');}
      });
    });
    });
     require(['jquery'],function($){
          if( $(".toggle .toggle-title").hasClass('active') ){ $(".toggle .toggle-title.active").closest('.toggle').find('.toggle-inner').show(); } $(".toggle .toggle-title").click(function(){ if( $(this).hasClass('active') ){ $(this).removeClass("active").closest('.toggle').find('.toggle-inner').slideUp(200); } else{ $(this).addClass("active").closest('.toggle').find('.toggle-inner').slideDown(200); } });
          $( ".product-item .product-image-photo" )
          .on( "mouseenter", function() {
            $( this ).closest( ".product-item" ).find(".weltpixel_quickview_button_v1").show();
          })
          .on( "mouseleave", function() {
            $( this ).closest( ".product-item" ).find(".weltpixel_quickview_button_v1").hide();
          });
           $( ".weltpixel_quickview_button_v1" )
          .on( "mouseenter", function() {
            $( this ).show();
          })
          .on( "mouseleave", function() {
            $( this ).hide();
          });
         $(document).on("click", ".openClickTab", function(){
             if($(this).hasClass( "active" )){
                 window.location = $(this).attr("data-href");
                return false;
             }
             tabname = $(this).attr("data-id");
             $this = $(this);
    	    var i, tabcontent, tablinks;
    	    tabcontent = document.getElementsByClassName("tabcontent");
    	    for (i = 0; i < tabcontent.length; i++) {
    	        tabcontent[i].style.display = "none";
    	    }
    	    tablinks = document.getElementsByClassName("tablinks");
    	    for (i = 0; i < tablinks.length; i++) {
    	        tablinks[i].className = tablinks[i].className.replace(" active", "");
    	    }
    	    
    	    $("#"+tabname).animate({
								            width: 'toggle',height: 'toggle',
								        });
    	   $this.addClass("active");
    	    return false;
         });
          $(document).on("dblclick", ".openClickTab", function(){
                window.location = $(this).attr("data-href");
                return false;
          });

    	$(document).on("click", ".mega-menu-parent", function(){
    		$this = $(this);
    		megaid = $this.attr("data-id");
    		jQuery(".mega-menu-parent").each(function(index, el) {
    			mid = $(this).attr("data-id");
    			if( mid != megaid ){
	    			$(this).removeClass('active');
	    			$(mid).slideUp("fast");
    			}
    		});
    		$this.toggleClass('active');
    		$(megaid).animate({width: 'toggle',height: 'toggle'});
    	});
    	$(document).on("click", ".banner-div a.close-btn", function(){
    		$this = $(".mega-menu-parent");
    		$this.toggleClass('active');
    		megaid = $this.attr("data-id");
    		$(megaid).animate({width: 'toggle',height: 'toggle'}); 
    		return false;
    	});
    	$(document).on("click", "a.close-brand", function(){
    		$this = $(".shop-by-brand");
    		$this.toggleClass('active');
    		megaid = $this.attr("data-id");
    		$(megaid).animate({width: 'toggle',height: 'toggle'});
    		return false;
    	});
    	$(document).on("mouseover",".mega-menu-child",function(){
    	    $( ".magnifier-preview" ).css('visibility', 'hidden');
    	});
    	$(document).on("mouseout",".mega-menu-child",function(){
    	    $( ".magnifier-preview" ).css('visibility', 'visible');
    	});
        $(document).on("click","#sub-submit",function(e){
            e.preventDefault();
            subemail = $("#sub-email").val();
            if(subemail){
                $("#newsletter-validate-detail #newsletter").val(subemail).trigger('change');
            }else{
                alert("Please enter email address.");
            }
            return false;
        });
         $(document).on("change","#newsletter-validate-detail #newsletter",function(e){
              $("#newsletter-validate-detail .subscribe").trigger("click");
         });
      	$(document).on("click",".categorybtn",function(){
            		$this = $(this);
            		if($this.hasClass('selectcategory')){
            			$this.removeClass('selectcategory');
            			$this.closest('.leftlistcategory').removeClass('slideit');
            			$this.closest('.leftlistcategory').find('.block-title').removeClass('slideitblock');
            			$this.closest('.leftlistcategory').find('.block-content').slideUp('slow');
            			$this.html("✚");
            		}else{
            			$this.addClass('selectcategory');
            			$this.closest('.leftlistcategory').addClass('slideit');
            			$this.closest('.leftlistcategory').find('.block-title').addClass('slideitblock'); 
            			$this.closest('.leftlistcategory').find('.block-content').slideDown('slow');
            			$this.html("▬");
            		}
            	});
            	$(document).on("click",".selectaccordian",function(){
            		$this = $(this);
            		if($this.hasClass('selectcategory')){
            			$this.removeClass('selectcategory');
            			$this.closest('.block-list').removeClass('slideit');
            			$this.closest('.block-list').find('.block-title').removeClass('slideitblock');
            			$this.closest('.block-list').find('.block-content').slideUp('slow');
            			$this.html("✚");
            		}else{
            			$this.addClass('selectcategory');
            			$this.closest('.block-list').addClass('slideit');
            			$this.closest('.block-list').find('.block-title').addClass('slideitblock');
            			$this.closest('.block-list').find('.block-content').slideDown('slow');
            			$this.html("▬");
            		} 
            	});		
            	
	$(document).on( "click",".minicart_cancle", function(e){
   $('.block-shopping-cart').trigger('click');
});  

	$(document).on( "click","#product-addtocart-button", function(e){
   $('.block-shopping-cart').trigger('click');
});

	$(document).on( "click",".btn_chat", function(e){
	   /* alert('hi');*/
   $('.meshim_widget_widgets_BorderOverlay').trigger('click');
});

$(document).on( "click",".mfp-container", function(){
 $(this).find('.action-close').trigger('click');
});



$(document).on( "click",".table-checkout-shipping-method input", function(){
  sm = $(this).val();
  console.log("sm"+sm);
});
 
/*    $(".catalog-product-view .message-success").ready(function(){
                            $("html, body").animate({ scrollTop: 0 }, "slow");
                            setTimeout(function(){
                                $('.action.showcart').trigger('click');
                            }, 6000);
                        });*/
                        
    $(document).on("click",".checkout-cart-index .control.qty .button-action.plus",function(event){
         var timeoutPlus;
        event.preventDefault();
        $ht = $(this);
        $qty = $ht.closest(".control.qty").find(".input-text.qty");
        $qv = $qty.val();
       
        if($qv > 0){
            $qvn = parseInt($qv) + 1;
            $qty.val($qvn);
            if( timeoutPlus != undefined ) {
                clearTimeout(timeoutPlus)
            }
            
              timeoutPlus = setTimeout(function(){
            $(".save_update .action.update").trigger("click");
              }, 1000);
        }
        return false;
    });
    $(document).on("click",".checkout-cart-index .control.qty .button-action.minus",function(event){
        var timeoutPlus;
        event.preventDefault();
        $ht = $(this);
        $qty = $ht.closest(".control.qty").find(".input-text.qty");
        $qv = $qty.val();
        if($qv > 1){
            $qvn = parseInt($qv) - 1;
            $qty.val($qvn);
            if( timeoutPlus != undefined ) {
                clearTimeout(timeoutPlus)
            }
            
             timeoutPlus = setTimeout(function(){
            $(".save_update .action.update").trigger("click");
             }, 1000);
        }
         return false;
    });
    
    $(document).on("click",".action.nav-toggle",function(){
        $("html").addClass("nav-before-open");
        $("html").addClass("nav-open");
    });
    
    
  
    
    
    
    $(document).on("click",".checkout-cart-index #block-shipping",function(){
        $(".action.primary.checkout").trigger("click");
    });
    
    $(document).on("click",".nav-before-open .page-wrapper header,.nav-before-open .page-wrapper main,.nav-before-open .page-wrapper small",function(){
         $("html").removeClass("nav-before-open");
        $("html").removeClass("nav-open");
    });
    
      $(document).on("click", ".place-order-125", function(){
           $('.checkout-payment-method .payment-method._active .payment-method-content div.actions-toolbar .primary').trigger('click');
      });
      
      $('a.action.tocompare').click( function(){
    if ( $(this).hasClass('current') ) {
        $(this).removeClass('current');
    } else {
        $('a.action.tocompare').removeClass('current');
        $(this).addClass('current');    
    }
});
                      
                                 (function($) {
                $.fn.menumaker = function(options) {  
                 var cssmenu = $(this), settings = $.extend({
                   format: "dropdown",
                   sticky: false
                 }, options);
                 return this.each(function() {
                   $(this).find(".button").on('click', function(){
                     $(this).toggleClass('menu-opened');
                     var mainmenu = $(this).next('ul');
                     if (mainmenu.hasClass('open')) { 
                       mainmenu.slideToggle().removeClass('open');
                     }
                     else {
                       mainmenu.slideToggle().addClass('open');
                       if (settings.format === "dropdown") {
                         mainmenu.find('ul').show();
                       }
                     }
                   });
                   cssmenu.find('li ul').parent().addClass('has-sub');
                multiTg = function() {
                     cssmenu.find(".has-sub").prepend('<span class="submenu-button"></span>');
                     cssmenu.find('.submenu-button').on('click', function() {
                       $(this).toggleClass('submenu-opened');
                       if ($(this).siblings('ul').hasClass('open')) {
                         $(this).siblings('ul').removeClass('open').slideToggle();
                       }
                       else {
                         $(this).siblings('ul').addClass('open').slideToggle();
                       }
                     });
                   };
                   if (settings.format === 'multitoggle') multiTg();
                   else cssmenu.addClass('dropdown');
                   if (settings.sticky === true) cssmenu.css('position', 'fixed');
                resizeFix = function() {
                  var mediasize = 1000;
                     if ($( window ).width() > mediasize) {
                       cssmenu.find('ul').show();
                     }
                     if ($(window).width() <= mediasize) {
                       cssmenu.find('ul').hide().removeClass('open');
                     }
                   };
                   resizeFix();
                   return $(window).on('resize', resizeFix);
                 });
                  };
                })(jQuery);
                
                (function($){
                $(document).ready(function(){
                $("#cssmenu").menumaker({
                   format: "multitoggle"
                });
                });
                })(jQuery);



                        
 });
 

</script>