<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_WebAr
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<script>
    require([
        "prototype"
    ], function () {
        window.customUrl = '<?= $escaper->escapeUrl($block->getViewModel()->getMediaUrl()) ?>';
        window.deleteText = '<?= $escaper->escapeHtml(__("Delete ")) ?>';
    });
</script>
