<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_AdvancedHidePrice
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
use Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Multi;

// @codingStandardsIgnoreFile

?>
<?php /* @var $block Multi */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<?php $helper = $this->helper("Bss\AdvancedHidePrice\Helper\Data") ?>
<div class="field option <?= ($_option->getRequired()) ? ' required' : '' ?>">
    <label class="label" for="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <?php if ($block->showSingle()): ?>
            <?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
            <?php $disable = ''; ?>
            <?php if ($block->getProduct()->getActiveCallHidePrice()): ?>
                <?php $disable = $helper->activeCallHidePrice($block->getProduct()) ? "disabled" : '';  ?>
                <?php if ($block->getProduct()->getActiveCallHidePrice() == "callforprice"): ?>
                    <div id="callforprice" class="callforprice-container callforprice_<?= $block->escapeHtml($_selections[0]->getId()); ?>">
                        <input type="hidden" name="product" value="<?= $block->escapeHtml($_selections[0]->getId()); ?>">
                        <input type="hidden" name="product_name" value="<?= $block->escapeHtml(__($_selections[0]->getName())); ?>">
                        <a class="callforprice_clickme action primary"><?= $block->escapeHtml(__($helper->getCallforpriceText($block->getProduct()))); ?></a>
                    </div>
                <?php endif; ?>
                <?php if ($block->getProduct()->getActiveCallHidePrice() == "hideprice"): ?>
                    <div id="callforprice_text" class="callforprice-container callforprice_text">
                        <?= $block->escapeHtml(__($helper->getCallforpriceText($block->getProduct()))); ?>
                    </div>
                <?php endif; ?>
            <?php elseif ($_selections[0]->getActiveCallHidePrice()) : ?>
                <?php $disable = $helper->activeCallHidePrice($_selections[0]) ? "disabled" : '';  ?>
                <?php if ($_selections[0]->getActiveCallHidePrice() == "callforprice"): ?>
                    <div id="callforprice" class="callforprice-container callforprice_<?= $block->escapeHtml($_selections[0]->getId()); ?>">
                        <input type="hidden" name="product" value="<?= $_selections[0]->getId(); ?>">
                        <input type="hidden" name="product_name" value="<?= $block->escapeHtml(__($_selections[0]->getName())); ?>">
                        <a class="callforprice_clickme action primary"><?= $block->escapeHtml(__($helper->getCallforpriceText($_selections[0]))); ?></a>
                    </div>
                <?php endif; ?>
                <?php if ($_selections[0]->getActiveCallHidePrice() == "hideprice"): ?>
                    <div id="callforprice_text" class="callforprice-container callforprice_text">
                        <?= $block->escapeHtml(__($helper->getCallforpriceText($_selections[0]))); ?>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
            <input type="hidden"
                   name="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>]"
                <?= $disable; ?>
                   value="<?= $block->escapeHtml($_selections[0]->getSelectionId()) ?>"/>
        <?php else: ?>
            <select multiple="multiple"
                    size="5"
                    id="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>"
                    name="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>][]"
                    data-selector="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>][]"
                    class="bundle-option-<?= $block->escapeHtml($_option->getId()) ?> multiselect product bundle option change-container-classname"
                <?php if ($_option->getRequired()) {
    echo 'data-validate={required:true}';
} ?>>
                <?php if (!$_option->getRequired()): ?>
                    <?php if (!$_option->getData('bssClasses')): ?>
                    <option value=""><?= /* @escapeNotVerified */ __('None') ?></option>
                    <?php endif; ?>
                <?php endif; ?>
                <?php foreach ($_selections as $_selection): ?>
                    <option value="<?= $block->escapeHtml($_selection->getSelectionId()) ?>"
                        <?php if ($block->isSelected($_selection)) {
    echo ' selected="selected"';
} ?>
                        <?php if ($helper->activeCallHidePrice($_selection) || $block->getProduct()->getActiveCallHidePrice()) {
    echo ' disabled="disabled"';
} ?>
                        <?php if (!$_selection->isSaleable()) {
    echo ' disabled="disabled"';
} ?>>
                        <?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>
    </div>
</div>
