<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_AdvancedHidePrice
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
use Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Select;

// @codingStandardsIgnoreFile

?>

<?php /* @var $block Select */ ?>
<?php $_option      = $block->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php [$_defaultQty, $_canChangeQty] = $block->getDefaultValues(); ?>
<?php $helper = $this->helper("Bss\AdvancedHidePrice\Helper\Data") ?>
<?php $selector = $helper->getSelector() ? $helper->getSelector() : ".action.tocart"; ?>
<div class="field option <?= ($_option->getRequired()) ? 'required' : '' ?>">
    <label class="label" for="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <?php if ($block->showSingle()): ?>
            <?= /* @escapeNotVerified */ $block->getSelectionTitlePrice($_selections[0]) ?>
            <?php $disable = ''; ?>
            <?php if ($block->getProduct()->getActiveCallHidePrice()): ?>
                <?php $disable = $helper->activeCallHidePrice($block->getProduct()) ? "disabled" : '';  ?>
                <?php if ($block->getProduct()->getActiveCallHidePrice() == "callforprice"): ?>
                    <div id="callforprice" class="callforprice-container callforprice_<?= $block->escapeHtml($_selections[0]->getId()); ?>">
                        <input type="hidden" name="product" value="<?= $block->escapeHtml($_selections[0]->getId()); ?>">
                        <input type="hidden" name="product_name" value="<?= $block->escapeHtml(__($_selections[0]->getName())); ?>">
                        <a class="callforprice_clickme action primary"><?= $block->escapeHtml(__($helper->getCallforpriceText($block->getProduct()))); ?></a>
                    </div>
                <?php endif; ?>
                <?php if ($block->getProduct()->getActiveCallHidePrice() == "hideprice"): ?>
                    <div id="callforprice_text" class="callforprice-container callforprice_text">
                        <?= $block->escapeHtml(__($helper->getCallforpriceText($block->getProduct()))); ?>
                    </div>
                <?php endif; ?>
            <?php elseif ($_selections[0]->getActiveCallHidePrice()) : ?>
                <?php $disable = $helper->activeCallHidePrice($_selections[0]) ? "disabled" : '';  ?>
                <?php if ($_selections[0]->getActiveCallHidePrice() == "callforprice"): ?>
                    <div id="callforprice" class="callforprice-container callforprice_<?= $_selections[0]->getId(); ?>">
                        <input type="hidden" name="product" value="<?= $block->escapeHtml($_selections[0]->getId()); ?>">
                        <input type="hidden" name="product_name" value="<?= $block->escapeHtml(__($_selections[0]->getName())); ?>">
                        <a class="callforprice_clickme action primary"><?= $block->escapeHtml(__($helper->getCallforpriceText($_selections[0]))); ?></a>
                    </div>
                <?php endif; ?>
                <?php if ($_selections[0]->getActiveCallHidePrice() == "hideprice"): ?>
                    <div id="callforprice_text" class="callforprice-container callforprice_text">
                        <?= $block->escapeHtml(__($helper->getCallforpriceText($_selections[0]))); ?>
                    </div>
                <?php endif; ?>
            <?php endif; ?>

            <input type="hidden"
                   class="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>  product bundle option"
                <?= $disable; ?>
                   name="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>]"
                   value="<?= $block->escapeHtml($_selections[0]->getSelectionId()) ?>"/>
        <?php else:?>
            <select id="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>"
                    name="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>]"
                    data-selector="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>]"
                    class="bundle-option-<?= $block->escapeHtml($_option->getId()) ?> product bundle option bundle-option-select change-container-classname"
                <?php if ($_option->getRequired()) {
    echo 'data-validate = {required:true}';
} ?>>
                <option value=""><?= /* @escapeNotVerified */ __('Choose a selection...') ?></option>
                <?php $callHidePriceIds = []; ?>
                <?php foreach ($_selections as $_selection): ?>
                    <?php if ($block->getProduct()->getActiveCallHidePrice()): ?>
                        <?php
                            $callHidePriceIds[$_selection->getSelectionId()] = [
                                "notify_text" => $block->escapeHtml(__($block->getProduct()->getCallforpriceText())),
                                "product_name" => $block->escapeHtml(__($_selection->getName())),
                                "type_callprice" => $block->getProduct()->getActiveCallHidePrice()
                            ];
                        ?>
                    <?php elseif ($_selection->getActiveCallHidePrice()): ?>
                        <?php
                            $callHidePriceIds[$_selection->getSelectionId()] = [
                                "notify_text" => $block->escapeHtml(__($helper->getCallforpriceText($_selection))),
                                "product_name" =>$block->escapeHtml(__($_selection->getName())),
                                "type_callprice" => $_selection->getActiveCallHidePrice()
                            ];
                        ?>
                    <?php else: ?>
                        <?php
                            $callHidePriceIds[$_selection->getSelectionId()] = [
                                "notify_text" => false,
                                "product_name" => false,
                                "type_callprice" => 'disabledCallForPrice'
                            ];
                        ?>
                    <?php endif; ?>
                    <?php $value = $_selection->getActiveCallHidePrice() || $block->getProduct()->getActiveCallHidePrice() ? "" : $_selection->getSelectionId();  ?>
                    <option value="<?= $block->escapeHtml($value)?>"
                            data-option="<?= $_selection->getSelectionId(); ?>"
                        <?php if ($block->isSelected($_selection)) {
                        echo ' selected="selected"';
                    } ?>
                        <?php if (!$_selection->isSaleable()) {
                        echo ' disabled="disabled"';
                    } ?>>
                        <?= /* @escapeNotVerified */ $block->getSelectionTitlePrice($_selection, true) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <div id="callforprice" class="callforprice-container callforprice-bundle-option">
                <input type="hidden" name="product" value="" />
                <input type="hidden" name="product_name" value="" />
                <a class="callforprice_clickme action primary"></a>
            </div>

            <div id="callforprice_text" class="callforprice-container callforprice_text"></div>
        <?php endif; ?>
        <?php  if (!$_option->getData('bssClasses')): ?>
        <div class="nested">
            <div class="field qty qty-holder">
                <label class="label" for="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>-qty-input">
                    <span><?= /* @escapeNotVerified */ __('Quantity') ?></span>
                </label>
                <div class="control">
                    <input id="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>-qty-input"
                        class="input-text qty <?= !$_canChangeQty ? 'qty-disabled' : '' ?>"
                        type="number"
                        name="bundle_option_qty[<?= $block->escapeHtml($_option->getId()) ?>]"
                        data-selector="bundle_option_qty[<?= $block->escapeHtml($_option->getId()) ?>]"
                        value="<?= $block->escapeHtml($_defaultQty) ?>" <?= !$_canChangeQty ? 'disabled':'' ?>/>
                </div>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>
<?php if (!empty($callHidePriceIds)): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Bss_AdvancedHidePrice/js/bundle_select": {
                    "callHidePriceIds" : <?= $helper->returnJson()->serialize($callHidePriceIds); ?>,
                    "selector" : "<?= $selector ?>"
                }
            }
        }
    </script>
<?php endif; ?>
