<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_AdvancedHidePrice
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
use Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Radio;

// @codingStandardsIgnoreFile

?>
<?php /* @var $block Radio */ ?>
<?php $_option = $block->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php [$_defaultQty, $_canChangeQty] = $block->getDefaultValues(); ?>
<?php $helper = $this->helper("Bss\AdvancedHidePrice\Helper\Data") ?>

<div class="field option <?= ($_option->getRequired()) ? 'required' : '' ?>">
    <label class="label">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
                <?= /* @escapeNotVerified */ $block->getSelectionTitlePrice($_selections[0]) ?>
                <?php $disable = ''; ?>
                <?php if (!$_selections[0]->getActiveCallHidePrice() && !$block->getProduct()->getActiveCallHidePrice()): ?>
                    <input type="hidden"
                           class="bundle-option-<?= (int)$_option->getId() ?> product bundle option"
                        <?= $disable; ?>
                           name="bundle_option[<?= (int)$_option->getId() ?>]"
                           value="<?= (int)$_selections[0]->getSelectionId() ?>"
                           id="bundle-option-<?= (int)$_option->getId() ?>-<?= (int)$_selections[0]->getSelectionId() ?>"
                           checked="checked"
                    />
                    <div class="field qty qty-holder">
                        <label class="label" for="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>-qty-input">
                            <span><?= /* @escapeNotVerified */ __('Quantity') ?></span>
                        </label>
                        <div class="control">
                            <input id="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>-qty-input"
                                   class="input-text qty <?= !$_canChangeQty ? 'qty-disabled' : '' ?>"
                                   type="number"
                                   name="bundle_option_qty[<?= $block->escapeHtml($_option->getId()) ?>]"
                                   data-selector="bundle_option_qty[<?= $block->escapeHtml($_option->getId()) ?>]"
                                   value="<?= $block->escapeHtml($_defaultQty) ?>" <?= !$_canChangeQty ? 'disabled':'' ?>/>
                        </div>
                    </div>
                <?php else: ?>
                    <?php if ($block->getProduct()->getActiveCallHidePrice()): ?>
                        <?php $disable = $helper->activeCallHidePrice($block->getProduct()) ? "disabled" : '';  ?>
                        <?php if ($block->getProduct()->getActiveCallHidePrice() == "callforprice"): ?>
                            <div id="callforprice" class="callforprice-container callforprice_<?= $block->escapeHtml($_selections[0]->getId()); ?>">
                                <input type="hidden" name="product" value="<?= $block->escapeHtml($_selections[0]->getId()); ?>">
                                <input type="hidden" name="product_name" value="<?= $block->escapeHtml(__($_selections[0]->getName())); ?>">
                                <a class="callforprice_clickme action primary"><?= $block->escapeHtml(__($helper->getCallforpriceText($block->getProduct()))); ?></a>
                            </div>
                        <?php endif; ?>
                        <?php if ($block->getProduct()->getActiveCallHidePrice() == "hideprice"): ?>
                            <div id="callforprice_text" class="callforprice-container callforprice_text">
                                <?= $block->escapeHtml(__($helper->getCallforpriceText($block->getProduct()))); ?>
                            </div>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php $disable = $helper->activeCallHidePrice($_selections[0]) ? "disabled" : '';  ?>
                        <?php if ($_selections[0]->getActiveCallHidePrice() == "callforprice"): ?>
                            <div id="callforprice" class="callforprice-container callforprice_<?= $_selections[0]->getId(); ?>">
                                <input type="hidden" name="product" value="<?= $_selections[0]->getId(); ?>">
                                <input type="hidden" name="product_name" value="<?= $block->escapeHtml(__($_selections[0]->getName())); ?>">
                                <a class="callforprice_clickme action primary"><?= $block->escapeHtml(__($helper->getCallforpriceText($_selections[0]))); ?></a>
                            </div>
                        <?php endif; ?>
                        <?php if ($_selections[0]->getActiveCallHidePrice() == "hideprice"): ?>
                            <div id="callforprice_text" class="callforprice-container callforprice_text">
                                <?= $block->escapeHtml(__($helper->getCallforpriceText($_selections[0]))); ?>
                            </div>
                        <?php endif; ?>
                        <input type="hidden"
                               class="bundle-option-<?= (int)$_option->getId() ?> product bundle option"
                            <?= $disable; ?>
                               name="bundle_option[<?= (int)$_option->getId() ?>]"
                               value="<?= (int)$_selections[0]->getSelectionId() ?>"
                               id="bundle-option-<?= (int)$_option->getId() ?>-<?= (int)$_selections[0]->getSelectionId() ?>"
                               checked="checked"
                        />
                    <?php endif; ?>
                <?php endif; ?>
            <?php else:?>
                <?php if (!$_option->getRequired()): ?>
                    <?php  if (!$_option->getData('bssClasses')): ?>
                        <div class="field choice">
                            <input type="radio"
                                   class="radio product bundle option"
                                   id="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>"
                                   name="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>]"
                                   data-selector="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>]"
                                <?= ($_default && $_default->isSalable()) ? '' : ' checked="checked" ' ?>
                                   value=""/>
                            <label class="label" for="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>">
                                <span><?= /* @escapeNotVerified */ __('None') ?></span>
                            </label>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
                <?php foreach ($_selections as $_selection): ?>
                    <div class="field choice">
                        <?php if ($block->getProduct()->getActiveCallHidePrice()): ?>
                            <label class="label"
                                   for="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>-<?= $block->escapeHtml($_selection->getSelectionId()) ?>">
                                <span><?= /* @escapeNotVerified */ $block->getSelectionTitlePrice($_selection) ?></span>
                            </label>
                            <?php if ($block->getProduct()->getActiveCallHidePrice() == "callforprice"): ?>
                                <div id="callforprice" class="callforprice-container callforprice_<?= $_selection->getId(); ?>">
                                    <input type="hidden" name="product" value="<?= $block->escapeHtml($_selection->getId()); ?>">
                                    <input type="hidden" name="product_name" value="<?= $block->escapeHtml(__($_selection->getName())); ?>">
                                    <a class="callforprice_clickme action primary"><?= $block->escapeHtml(__($helper->getCallforpriceText($block->getProduct()))) ?></a>
                                </div>
                            <?php endif; ?>
                            <?php if ($block->getProduct()->getActiveCallHidePrice() == "hideprice"): ?>
                                <div id="callforprice_text" class="callforprice-container callforprice_text">
                                    <?= $block->escapeHtml(__($helper->getCallforpriceText($block->getProduct()))) ?>
                                </div>
                            <?php endif; ?>
                        <?php else : ?>
                            <?php if (!$helper->activeCallHidePrice($_selection)): ?>
                                <input type="radio"
                                       class="radio product bundle option change-container-classname"
                                       id="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>-<?= $block->escapeHtml($_selection->getSelectionId()) ?>"
                                    <?php if ($_option->getRequired()) {
                                        echo 'data-validate="{\'validate-one-required-by-name\':true}"';
                                    }?>
                                       name="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>]"
                                       data-selector="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>]"
                                    <?php if ($block->isSelected($_selection)) {
                                        echo ' checked="checked"';
                                    } ?>
                                    <?php if (!$_selection->isSaleable()) {
                                        echo ' disabled="disabled"';
                                    } ?>
                                       value="<?= $block->escapeHtml($_selection->getSelectionId()) ?>"/>
                            <?php endif; ?>
                            <label class="label"
                                   for="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>-<?= $block->escapeHtml($_selection->getSelectionId()) ?>">
                                <span><?= /* @escapeNotVerified */ $block->getSelectionTitlePrice($_selection) ?></span>
                            </label>
                            <?php if ($_selection->getActiveCallHidePrice() == "callforprice"): ?>
                                <div id="callforprice" class="callforprice-container callforprice_<?= $_selection->getId(); ?>">
                                    <input type="hidden" name="product" value="<?= $block->escapeHtml($_selection->getId()); ?>">
                                    <input type="hidden" name="product_name" value="<?= $block->escapeHtml(__($_selection->getName())); ?>">
                                    <a class="callforprice_clickme action primary"><?= $block->escapeHtml(__($helper->getCallforpriceText($_selection))); ?></a>
                                </div>
                            <?php endif; ?>
                            <?php if ($_selection->getActiveCallHidePrice() == "hideprice"): ?>
                                <div id="callforprice_text" class="callforprice-container callforprice_text">
                                    <?= $block->escapeHtml(__($helper->getCallforpriceText($_selection))); ?>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
                <div id="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>-container"></div>
            <?php endif; ?>
            <?php  if (!$_option->getData('bssClasses')): ?>
                <div class="field qty qty-holder">
                    <label class="label" for="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>-qty-input">
                        <span><?= /* @escapeNotVerified */ __('Quantity') ?></span>
                    </label>
                    <div class="control">
                        <input <?php if (!$_canChangeQty) {
                            echo ' disabled="disabled"';
                        } ?>
                                id="bundle-option-<?= $block->escapeHtml($_option->getId()) ?>-qty-input"
                                class="input-text qty<?php if (!$_canChangeQty) {
                                    echo ' qty-disabled';
                                } ?>"
                                type="number"
                                name="bundle_option_qty[<?= $block->escapeHtml($_option->getId()) ?>]"
                                data-selector="bundle_option_qty[<?= $block->escapeHtml($_option->getId()) ?>]"
                                value="<?= $block->escapeHtml($_defaultQty) ?>"/>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
