<fieldset class="fieldset create account" data-hasrequired="<?= /* @noEscape*/ __('* Required Fields') ?>">
    <div style="font-size:13px;font-weight:bold;margin-top:10px;"><?= /* @noEscape*/ __('Receive all your Order Related Notifications Directly on your WhatsApp.') ?></div>
    <legend class="legend">
    
    </legend>
    <div id="smserrordiv" name="smserrordiv" class="message error"></div>
    <div id="smssuccessdiv" name="smssuccessdiv" class="message success"></div>
    <div class="field">
        <div class="control">
            <input type="text" name="mobilenumber" id="mobilenumber" title="<?= /* @noEscape*/ __('WhatsApp Number') ?>" class="input-text mobilenumber" autocomplete="off" placeholder="WhatsApp Number" maxlength="12" pattern="[0-9]">
            <input type="hidden" value="" id="countryreg" name="countryreg" >
        </div>
        <div id="smserror" name="smserror" generated="true" class="mage-error"></div>
        <?php if (!$block->getCountryFlagEnable()): ?>
        <div class="comment flagdisableregister" style="float: left;"><?= /* @noEscape*/ __('Enter WhatsApp Number With Country code & without any sign. e.g:-(91xxxxxxxx09)') ?></div>
        <?php endif;?>
        <div id="otpdiv" class="control">
            <input type="password" name="otp" id="otp" title="<?= /* @noEscape*/ __('otp') ?>" class="input-text" autocomplete="off" placeholder="OTP" maxlength="10">
        </div>
        <div id="waitsmsdiv">
            <img src='<?= /* @noEscape*/ $block->getViewFileUrl('images/loader-1.gif'); ?>' alt="Please Wait..." width="30px" height="30px">
        </div>
        <div id="otpbtndiv">
            <button id="getotpbtn" name="getotpbtn" type="button" class="<?= /* @noEscape*/ $block->getButtonclass();?>" title="Get OTP">
                <span><?= /* @noEscape*/ __('Get OTP') ?></span>
            </button>
            <button id="resendotpbtn" name="resendotpbtn" type="button" class="<?= /* @noEscape*/ $block->getButtonclass();?>" title="Resend OTP">
                <span><?= /* @noEscape*/ __('Resend OTP') ?></span>
            </button>
        </div>
        <div style="clear: both;"></div>
        <div id="confirmationdiv">
            <button id="confirmotpbtn" name="confirmotpbtn" type="button" class="<?= /* @noEscape*/ $block->getButtonclass();?>" title="Verify Mobile Number">
                <span><?= /* @noEscape*/ __('Verify WhatsApp Number') ?></span>
            </button>
        </div>
        <div style="clear: both;"></div>
        <div id="existingnumberdiv">
            <p class="empty"><?= /* @noEscape*/ __('Please verify your WhatsApp Number before proceeding to checkout.') ?></p>
        </div>
        <div id="procedtocheckoutdiv">
            <button id="procedtocheckoutbtn" name="procedtocheckoutbtn" type="button" class="<?= /* @noEscape*/ $block->getButtonclass();?>" title="Proceed to Checkout">
                <span><?= /* @noEscape*/ __('Proceed to Checkout') ?></span>
            </button>
        </div>
    </div>
</fieldset>
<script>
    require(['jquery', 'jquery/ui','Magecomp_Whatsappultimate/countryflag/js/intlTelInput.min'], function($)
    {
        function Smsresetdata()
        {
            $('#mobilenumber').removeClass('mage-error');
            $('#otp').removeClass('mage-error');
            $('#smserrordiv').hide();
            $('#smserrordiv').html('');
        }

        function Smstoggeldata(Elementid)
        {
            $(Elementid).toggle();
        }
        <?php if ($block->getCountryFlagEnable()) { ?>
                 $("#getotpbtn").prop("disabled", true);
                var country_flag = "<?= /* @noEscape*/ $block->getDefaultCountry();?>";
                <?php if ($block->getCountryFlagDetectByIP()):?>
                    country_flag = "<?= /* @noEscape*/ $block->getGeoCountryCode();?>";
                <?php endif; ?>
                $("#mobilenumber").intlTelInput({
                    initialCountry: country_flag,
                    utilsScript: "<?= /* @noEscape*/ $block->getViewFileUrl('Magecomp_Whatsappultimate::countryflag/js/utils.js'); ?>"
                });

                $(".country-list li").on('click', function() {
                    $("#mobilenumber").val("");
                    jQuery("#getotpbtn").prop("disabled", true);
                    jQuery("#mobilenumber").attr('maxlength',12);
                });
                
                 $("#mobilenumber").keyup(function(){
                    Smsresetdata();
                    var str = $(".selected-flag").attr("title");
                    var countrycode =  str.split('+')[1];
                    var countrycodeval =  str.split('+')[1];
                    var mobilelength=$('#mobilenumber').val().length;
                    var mobile = countrycode + $('#mobilenumber').val();
                    $("#countryreg").val(countrycode);
                    var temp=true;
                    if(mobile == null || mobile == '')
                    {
                        temp=false;
                        $('#mobilenumber').addClass('mage-error');
                        $('#smserror').html('<?= /* @noEscape*/ __('This is a required field.') ?>');
                        return false;
                    }
                    if(!$.isNumeric(mobile) || mobile.substring(0,1)=='+' || mobile.substring(0,1)=='-')
                    {
                        temp=false;
                        $('#mobilenumber').addClass('mage-error');
                        $('#smserror').html('<?= /* @noEscape*/ __('Make sure, you have entered valid WhatsApp Number.') ?>');
                        return false;
                    }
                    var countrycode = jQuery(".flag-container > .country-list > .active").attr("data-country-code");

                    $.ajax({
                        type: "POST",
                        url: '<?= /* @noEscape*/ $block->getUrl('whatsappcountryflag/customer/validatephone')?>',
                        data:{'mobile':mobile,'countrycode':countrycode,'mobilelength':mobilelength,'country_id':countrycodeval},
                        success: function(data)
                        {
                            jQuery("#mobilenumber").attr('maxlength',data.digit);
                            if(data.validate==true){
                                $('#smserror').html('<?= /* @noEscape*/ __('') ?>');
                                $("#getotpbtn").prop("disabled", false);
                            }
                            else{
                                if(temp==true){
                                    $('#smserror').html(data.message);
                                }
                                $("#getotpbtn").prop("disabled", true);
                            }
                        },
                        error: function(data) {
                            $('#smserror').html('<?= /* @noEscape*/ __('Something went wrong, Try again later.') ?>');
                        }
                    });
                });
            <?php } ?>

                $("#getotpbtn").click(function(e)
                {
                    //Reset Everything
                    Smsresetdata();

                    //Number Validation
                    var mobile = $('#mobilenumber').val();
                    if(mobile == null || mobile == '')
                    {
                        $('#mobilenumber').addClass('mage-error');
                        $('#smserrordiv').show();
                        $('#smserrordiv').html('<?= /* @noEscape*/ __('Please, Enter Your WhatsApp Number.') ?>');
                        return false;
                    }
                    if(!$.isNumeric(mobile) || mobile.length <= 9)
                    {
                        $('#mobilenumber').addClass('mage-error');
                        $('#smserrordiv').show();
                        $('#smserrordiv').html('<?= /* @noEscape*/ __('Make sure, you have entered valid WhatsApp Number.') ?>');
                        return false;
                    }
                    <?php if ($block->getCountryFlagEnable()) { ?>
                        var countrycode = $("#countryreg").val();
                        mobile = countrycode.concat(mobile);
                    <?php } ?>

                    //Send OTP To Number
                    $.ajax({
                        type: "POST",
                        url: '<?= /* @noEscape*/ $block->getUrl('whatsappultimate/customer/checkoutotp')?>',
                        data:{'mobile':mobile},
                        beforeSend: function()
                        {
                            Smsresetdata();
                            Smstoggeldata('#getotpbtn');
                            Smstoggeldata('#waitsmsdiv');
                        },
                        success: function(data)
                        {
                            if(data == 'success')
                            {
                                Smstoggeldata('#waitsmsdiv');
                                Smstoggeldata('#otpdiv');
                                Smstoggeldata('#resendotpbtn');
                                Smstoggeldata('#confirmationdiv');
                                $('#mobilenumber').attr('readonly', true);
                            }
                            else
                            {
                                Smstoggeldata('#waitsmsdiv');
                                Smstoggeldata('#getotpbtn');
                                $('#smserrordiv').show();
                                $('#smserrordiv').html(data);
                            }
                        },
                        error: function() {
                            Smstoggeldata('#waitsmsdiv');
                            Smstoggeldata('#getotpbtn');
                            $('#smserrordiv').show();
                            $('#smserrordiv').html('<?= /* @noEscape*/ __('Something Went Wrong, Try Again Later.') ?>');
                        }
                    });
                });

                $("#resendotpbtn").click(function(e)
                {
                    //Reset Everything
                    Smsresetdata();

                    var mobile = $('#mobilenumber').val();
                    <?php if ($block->getCountryFlagEnable()) { ?>
                        var countrycode = $("#countryreg").val();
                        mobile = countrycode.concat(mobile);
                    <?php } ?>
                    
                    //Re-Send OTP To Number
                    $.ajax({
                        type: "POST",
                        url: '<?= /* @noEscape*/ $block->getUrl('whatsappultimate/customer/checkoutotp')?>',
                        data:{'mobile':mobile},
                        beforeSend: function()
                        {
                            Smsresetdata();
                            Smstoggeldata('#resendotpbtn');
                            Smstoggeldata('#waitsmsdiv');
                            Smstoggeldata('#confirmationdiv');
                        },
                        success: function(data)
                        {
                            Smstoggeldata('#waitsmsdiv');
                            Smstoggeldata('#confirmationdiv');
                            if(data != 'success')
                            {
                                $('#smserrordiv').show();
                                $('#smserrordiv').html(data);
                            }
                        },
                        error: function() {
                            Smstoggeldata('#waitsmsdiv');
                            $('#smserrordiv').show();
                            $('#smserrordiv').html('<?= /* @noEscape*/ __('Something Went Wrong, Try Again Later.') ?>');
                        }
                    });
                });

             $("#confirmotpbtn").click(function(e)
                {
                    //OTP Validation
                    var otpstring = $('#otp').val();
                    if(otpstring == null || otpstring == '')
                    {
                        $('#otp').addClass('mage-error');
                        $('#smserrordiv').show();
                        $('#smserrordiv').html('<?= /* @noEscape*/ __('Please, Enter OTP.') ?>');
                        return false;
                    }

                    var mobile = $('#mobilenumber').val();

                    <?php if ($block->getCountryFlagEnable()) { ?>
                        var countrycode = $("#countryreg").val();
                        mobile = countrycode.concat(mobile);
                    <?php }?>

                    //Verify Mobile & OTP
                    $.ajax({
                        type: "POST",
                        url: '<?= /* @noEscape*/ $block->getUrl('whatsappultimate/customer/checkoutotpnumber')?>',
                        data:{'mobile':mobile,'otp':otpstring},
                        beforeSend: function()
                        {
                            Smsresetdata();
                            Smstoggeldata('#otpbtndiv');
                            Smstoggeldata('#waitsmsdiv');
                            Smstoggeldata('#confirmationdiv');
                        },
                        success: function(data)
                        {
                            Smstoggeldata('#waitsmsdiv');
                            if(data == 'success')
                            {
                                $('#smssuccessdiv').html('<?= /* @noEscape*/ __('Your Mobile Number is Verified Successfully! Now You Can Proceed to Checkout.') ?>');
                                $('#smssuccessdiv').show();
                                $('#procedtocheckoutdiv').show();
                            }
                            else
                            {
                                $('#smserrordiv').html(data);
                                Smstoggeldata('#smserrordiv');
                                Smstoggeldata('#confirmationdiv');
                            }
                        },
                        error: function() {
                            Smstoggeldata('#waitsmsdiv');
                            Smstoggeldata('#confirmationdiv');
                            $('#smserrordiv').html('<?= /* @noEscape*/ __('Something Went Wrong, Try Again Later.') ?>');
                            Smstoggeldata('#smserrordiv');
                        }
                    });
                    });

        $("#procedtocheckoutbtn").click(function(e) {
            window.location.href = '<?= /* @noEscape*/ $block->getCheckoutURL(); ?>';
        });

    });
</script>
