<?php if ($block->getApiGateway()!="whatsappdialog360api"): ?>
<style type="text/css">
    #row_usertemplate_usersignupconfirm_lang_code{
        display:none;
    }
    #row_usertemplate_usersignupconfirm_tmp_id{
        display: none;
    }
    #row_usertemplate_usersignupconfirm_parms{
         display: none;
    }
    #row_usertemplate_usersignup_lang_code{
        display: none;
    }
    #row_usertemplate_usersignup_tmp_id{
        display: none;
    }
    #row_usertemplate_usersignup_parms{
         display: none;
    }
    #row_usertemplate_usermobileconfirm_lang_code{
         display: none;
    }
    #row_usertemplate_usermobileconfirm_tmp_id{
         display: none;
    }
    #row_usertemplate_usermobileconfirm_parms{
         display: none;
    }
    #row_usertemplate_userorderconfirm_lang_code{
         display: none;
    }
    #row_usertemplate_userorderconfirm_tmp_id{
         display: none;
    }
    #row_usertemplate_userorderconfirm_parms{
         display: none;
    }
    #row_usertemplate_userorderplace_lang_code{
         display: none;
    }
    #row_usertemplate_userorderplace_tmp_id{
         display: none;
    }
    #row_usertemplate_userorderplace_parms{
         display: none;
    }
    #row_usertemplate_userinvoice_lang_code{
         display: none;
    }
    #row_usertemplate_userinvoice_tmp_id{
         display: none;
    }
    #row_usertemplate_userinvoice_parms{
         display: none;
    }
    #row_usertemplate_usershipment_lang_code{
         display: none;
    }
    #row_usertemplate_usershipment_tmp_id{
         display: none;
    }
    #row_usertemplate_usershipment_parms{
         display: none;
    }
    #row_usertemplate_usercreditmemo_lang_code{
         display: none;
    }
    #row_usertemplate_usercreditmemo_tmp_id{
         display: none;
    }
    #row_usertemplate_usercreditmemo_parms{
         display: none;
    }
    #row_usertemplate_usercontactus_lang_code{
         display: none;
    }
     #row_usertemplate_usercontactus_tmp_id{
         display: none;
    }
     #row_usertemplate_usercontactus_parms{
         display: none;
    }


    #row_admintemplate_adminsignup_lang_code{
         display: none;
    }
    #row_admintemplate_adminsignup_tmp_id{
         display: none;
    }
    #row_admintemplate_adminsignup_parms{
         display: none;
    }
    #row_admintemplate_adminorderplace_lang_code{
         display: none;
    }
     #row_admintemplate_adminorderplace_tmp_id{
         display: none;
    }
     #row_admintemplate_adminorderplace_parms{
         display: none;
    }
    #row_admintemplate_admininvoice_lang_code{
         display: none;
    }
    #row_admintemplate_admininvoice_tmp_id{
         display: none;
    }
    #row_admintemplate_admininvoice_parms{
         display: none;
    }
    #row_admintemplate_adminshipment_lang_code{
         display: none;
    }
    #row_admintemplate_adminshipment_tmp_id{
         display: none;
    }
    #row_admintemplate_adminshipment_parms{
         display: none;
    }
    #row_admintemplate_admincreditmemo_lang_code{
         display: none;
    }
    #row_admintemplate_admincreditmemo_tmp_id{
         display: none;
    }
    #row_admintemplate_admincreditmemo_parms{
         display: none;
    }
    #row_admintemplate_admincontactus_lang_code{
         display: none;
    }
    #row_admintemplate_admincontactus_tmp_id{
         display: none;
    }
    #row_admintemplate_admincontactus_parms{
         display: none;
    }

</style>
<?php endif; ?>

