<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>

<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Language') ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
            <strong class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <span style="display: inline-block;padding-right: 35px;background-position: 94% 42%!important;
 background-size: auto 100%;background-repeat: no-repeat;background-image:url('<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/flags/flag_' . $block->escapeHtml($block->getCurrentStoreCode()) . '.png') ?>');"><?php if( trim($block->escapeHtml($block->getStoreName())) == "English" ){ echo "انجليزي"; }elseif(trim($block->escapeHtml($block->getStoreName())) == "Arabic"){ echo "عربي"; }else{ echo trim($block->escapeHtml($block->getStoreName())); } ?></span>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown"
            data-mage-init='{"dropdownDialog":{
                "appendTo":"#switcher-language<?php /* @escapeNotVerified */ echo $id ?> > .options",
                "triggerTarget":"#switcher-language-trigger<?php /* @escapeNotVerified */ echo $id ?>",
                "closeOnMouseLeave": false,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":null}}'>
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>' style="display: inline-block; background-position: 10% 50%; padding-left: 35px;background-repeat: no-repeat;background-image:url('<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/flags/flag_' . $block->escapeHtml($_lang->getCode()) . '.png') ?>');" >
                            <?php if( trim($block->escapeHtml($_lang->getName())) == "English" ){ echo "انجليزي"; }elseif(trim($block->escapeHtml($_lang->getName())) == "Arabic"){ echo "عربي"; }else{ echo trim($block->escapeHtml($_lang->getName())); } ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
