<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_DynamicCategory
 * @author     Extension Team
 * @copyright  Copyright (c) 2023 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/** @var \Magento\Backend\Block\Widget\Form\Renderer\Fieldset $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php $_element = $block->getElement() ?>
<?php $_jsObjectName = $block->getFieldSetId() != null ? $block->getFieldSetId() : $_element->getHtmlId() ?>
<div class="rule-tree bss-dynamic-category-rule-tree">
    <fieldset id="<?= $escaper->escapeHtmlAttr($_jsObjectName) ?>" <?= /* @noEscape */ $_element->serialize(['class']) ?>
              class="fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml($_element->getLegend()) ?></span></legend>
        <br>
        <?php if ($_element->getComment()): ?>
            <div class="messages">
                <div class="message message-notice"><?= $escaper->escapeHtml($_element->getComment()) ?></div>
            </div>
        <?php endif; ?>
        <div class="rule-tree-wrapper">
            <?= $_element->getChildrenHtml() ?>
            <div data-mage-init='{"Bss_DynamicCategory/js/category/productPreview": {"url": "<?= $escaper->escapeUrl($block->getUrl('dynamic_category/rule/productpreview', ['form_key' => $block->getFormKey(), 'loadGrid' => 1])) ?>"}}'
                 class="bss-dynamic-category-button">
                <button type="button" class="show-details"><?= $escaper->escapeHtml(__('Refresh matching products')) ?></button>
            </div>
            <div class="bss-dynamic-category-list"></div>
        </div>
    </fieldset>
</div>

<?php $scriptString = <<<script

require([
    'Magento_Rule/rules',
    'prototype'
], function(VarienRulesForm){

script;
$scriptString .= 'window.' . /* @noEscape */ $_jsObjectName . ' = new VarienRulesForm(\'' .
    /* @noEscape */ $_jsObjectName . '\', \'' .  /* @noEscape */ $block->getNewChildUrl() . '\');';
if ($_element->getReadonly()):
    $scriptString .= /* @noEscape */ $_element->getHtmlId() . '.setReadonly(true);' . PHP_EOL;
endif;

$scriptString .= '});' . PHP_EOL;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
