<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_DynamicCategory
 * @author     Extension Team
 * @copyright  Copyright (c) 2023 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/** @var \Bss\DynamicCategory\Block\Adminhtml\Catalog\Edit\Tab\ImportRule $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php
$category     = $block->getCategory();
?>
<div class="import-conditions-rule-block">
    <div class="admin__field-label bss-import-rule-label">
        <label>
            <span><?= $escaper->escapeHtml(__('Import Category Rules')) ?></span>
        </label>
    </div>
    <div class="admin__field-control bss-import-rule-conditions">
        <select name='import_conditions_field' class="admin__control-select">
            <?php foreach($category as $option) {
                if($option['value'] == '')
                { ?>
                    <option value=""><?= $escaper->escapeHtml(__('-- Please Select a Category --')) ?></option>
                <?php } else{ ?>
                    <option value="<?php echo $option['value'] ?>"><?php echo $option['label'] ?></option>
                <?php }} ?>
        </select>
    </div>
    <div data-mage-init='{"Bss_DynamicCategory/js/category/importRule": {"url": "<?= $escaper->escapeUrl($block->getUrl('dynamic_category/rule/import', ['form_key' => $block->getFormKey()])) ?>"}}'
         class="bss-dynamic-category-import-button">
        <button type="button" class="show-details"><?= $escaper->escapeHtml(__('Import')) ?></button>
    </div>
</div>



