<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_AIImageSearch
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

use Magento\Framework\Escaper;

/**
 * Catalog advanced search form
 *
 * @var $block \Magento\CatalogSearch\Block\Advanced\Form
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var Escaper $escaper
 */
?>

<?php
/** @var \Magento\CatalogSearch\Helper\Data $catalogSearchHelper */
$catalogSearchHelper = $block->getData('catalogSearchHelper'); ?>
<?php $maxQueryLength = $catalogSearchHelper->getMaxQueryLength();?>
<form class="form search advanced" action="<?= $escaper->escapeUrl($block->getSearchPostUrl()) ?>" method="get"
      id="form-validate">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Search Settings')) ?></span></legend><br />
        <?php foreach ($block->getSearchableAttributes() as $attribute): ?>
            <?php $_code = $attribute->getAttributeCode() ?>
            <div class="field <?= $escaper->escapeHtmlAttr($_code) ?>">
                <label class="label" for="<?= $escaper->escapeHtmlAttr($_code) ?>">
                    <span><?= $escaper->escapeHtml(__($block->getAttributeLabel($attribute))) ?></span>
                </label>
                <div class="control">
                    <?php
                    switch ($block->getAttributeInputType($attribute)):
                        case 'number':
                            ?>
                    <div class="range fields group group-2">
                        <div class="field no-label">
                            <div class="control">
                                <input type="text"
                                    name="<?= $escaper->escapeHtmlAttr($_code) ?>[from]"
                                    value="<?= $escaper->escapeHtml($block->getAttributeValue($attribute, 'from')) ?>"
                                    id="<?= $escaper->escapeHtmlAttr($_code) ?>"
                                    title="<?= $escaper->escapeHtml($block->getAttributeLabel($attribute)) ?>"
                                    class="input-text"
                                    maxlength="<?= $escaper->escapeHtmlAttr($maxQueryLength) ?>"
                                    data-validate="{number:true, 'less-than-equals-to':'#<?=
                                        $escaper->escapeHtmlAttr($_code) ?>_to'}" />
                            </div>
                        </div>
                        <div class="field no-label">
                            <div class="control">
                                <input type="text"
                                    name="<?= $escaper->escapeHtmlAttr($_code) ?>[to]"
                                    value="<?= $escaper->escapeHtml($block->getAttributeValue($attribute, 'to')) ?>"
                                    id="<?= $escaper->escapeHtmlAttr($_code) ?>_to"
                                    title="<?= $escaper->escapeHtml($block->getAttributeLabel($attribute)) ?>"
                                    class="input-text"
                                    maxlength="<?= $escaper->escapeHtmlAttr($maxQueryLength) ?>"
                                    data-validate="{number:true, 'greater-than-equals-to':'#<?=
                                        $escaper->escapeHtmlAttr($_code) ?>'}" />
                            </div>
                        </div>
                    </div>
                            <?php
                            break;
                        case 'price':
                            ?>
                    <div class="range price fields group group-2">
                        <div class="field no-label">
                            <div class="control">
                                <input name="<?= $escaper->escapeHtmlAttr($_code) ?>[from]"
                                    value="<?= $escaper->escapeHtml($block->getAttributeValue($attribute, 'from')) ?>"
                                    id="<?= $escaper->escapeHtmlAttr($_code) ?>"
                                    title="<?= $escaper->escapeHtml($block->getAttributeLabel($attribute)) ?>"
                                    class="input-text"
                                    type="text"
                                    maxlength="<?= $escaper->escapeHtmlAttr($maxQueryLength) ?>"
                                    data-validate="{
                                        number:true,
                                        'validate-not-negative-number':true,
                                        'less-than-equals-to':'#<?= $escaper->escapeHtmlAttr($_code) ?>_to'
                                    }" />
                            </div>
                        </div>
                        <div class="field with-addon no-label">
                            <div class="control">
                                <div class="addon">
                                    <input name="<?= $escaper->escapeHtmlAttr($_code) ?>[to]"
                                        value="<?= $escaper->escapeHtml($block->getAttributeValue($attribute, 'to')) ?>"
                                        id="<?= $escaper->escapeHtmlAttr($_code) ?>_to"
                                        title="<?= $escaper->escapeHtml($block->getAttributeLabel($attribute)) ?>"
                                        class="input-text"
                                        type="text"
                                        maxlength="<?= $escaper->escapeHtmlAttr($maxQueryLength) ?>"
                                        data-validate="{
                                            number:true,
                                            'validate-not-negative-number':true,
                                            'greater-than-equals-to':'#<?= $escaper->escapeHtmlAttr($_code) ?>'
                                        }" />
                                    <label class="addafter"
                                        for="<?= $escaper->escapeHtmlAttr($_code) ?>_to">
                                        <?= $escaper->escapeHtml($block->getCurrency($attribute)) ?>
                                    </label>
                                    <input type="hidden"
                                        name="<?= $escaper->escapeHtmlAttr($_code)?>[currency]"
                                        value="<?= $escaper->escapeHtml($block->getCurrency($attribute)) ?>">
                                </div>
                            </div>
                        </div>
                    </div>
                            <?php
                            break;
                        case 'select':
                            ?>
                            <?= /* @noEscape */ $block->getAttributeSelectElement($attribute) ?>
                            <?php
                            break;
                        case 'yesno':
                            ?>
                            <?= /* @noEscape */ $block->getAttributeYesNoElement($attribute) ?>
                            <?php
                            break;
                        case 'date':
                            ?>
                        <div class="range dates fields group group-2">
                            <div class="field date no-label">
                                <div class="control">
                                    <?= /* @noEscape */ $block->getDateInput($attribute, 'from') ?>
                                </div>
                            </div>
                            <div class="field date no-label">
                                <div class="control">
                                    <?= /* @noEscape */ $block->getDateInput($attribute, 'to') ?>
                                </div>
                            </div>
                        </div>
                            <?php
                            break;
                        default:
                            ?>
                        <input type="text"
                            name="<?= $escaper->escapeHtmlAttr($_code) ?>"
                            id="<?= $escaper->escapeHtmlAttr($_code) ?>"
                            value="<?= $escaper->escapeHtml($block->getAttributeValue($attribute)) ?>"
                            title="<?= $escaper->escapeHtml($block->getAttributeLabel($attribute)) ?>"
                            class="input-text <?= $escaper->escapeHtmlAttr($block->getAttributeValidationClass(
                                $attribute
                            ))?>"
                            maxlength="<?= $escaper->escapeHtmlAttr($maxQueryLength) ?>" />
                    <?php endswitch; ?>
                </div>
            </div>
        <?php endforeach; ?>
        <?php
        $viewModel = $block->getViewModel();
        ?>
        <label class="label">
            <span class="wk-ai-search-by-image-main-label"><?= $escaper->escapeHtml(__("Search By Image")) ?></span>
        </label>
        <div class="block wk-ai-search-by-image-main-container">
            <div class="wk-ai-search-by-image-image">
                <img class="wk-ai-search-by-image-orignal-image" 
                src="<?= $escaper->escapeHtml($viewModel->getPlaceholderImage()) ?>" alt="Orignal Image">
                <img class="wk-ai-search-by-image-cropped-image" 
                src="<?= $escaper->escapeHtml($viewModel->getPlaceholderImage()) ?>" alt="Cropped Image">
            </div>
            <div class="wk-ai-search-by-image-align-label-button-center">
                <div class="wk-ai-search-by-image-label-button">
                    <label class="wk-ai-search-by-image-label">
                        <?= $escaper->escapeHtml(__('AI Search By Image')) ?>
                    </label>
                    <span class="wk-ai-search-by-image-browse-button btn button">
                        <?= $escaper->escapeHtml(__('Browse Image')) ?>
                    </span>
                </div>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
    <div class="primary">
        <button type="submit"
                class="action search primary"
                title="<?= $escaper->escapeHtml(__('Search')) ?>">
            <span><?= $escaper->escapeHtml(__('Search')) ?></span>
        </button>
    </div>
    </div>
</form>
<input id="wk-ai-advanced-image-search-input" type="file" accept="image/png, image/gif, image/jpg, image/jpeg"/>
<?php $scriptString = <<<script
require([
    "jquery",
    "mage/mage",
    "mage/validation"
], function($){
    $('#form-validate').mage('validation', {
            errorPlacement: function (error, element) {
                var parent = element.parent();
                if (parent.hasClass('range')) {
                    parent.find(this.errorElement + '.' + this.errorClass).remove().end().append(error);
                } else {
                    error.insertAfter(element);
                }
            },
            messages: {
               'price[to]': {'greater-than-equals-to': '{$escaper->escapeJs(__('Please enter a valid price range.'))}'},
               'price[from]': {'less-than-equals-to': '{$escaper->escapeJs(__('Please enter a valid price range.'))}'}
            }
        });
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<script type="text/x-magento-init">
{
    "*" : {
        "Webkul_AIImageSearch/js/advanced-search-script": {}
    }
}
</script>
