<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_OrderDeliveryDate
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php /** @var \Bss\OrderDeliveryDate\Block\Adminhtml\Order\Delivery\Form $block */ ?>
<fieldset class="fieldset admin__fieldset-wrapper">
    <div class="form-inline">
        <?php echo $block->getForm()->toHtml() ?>
    </div>
</fieldset>
