define(['jquery'],function($){$.fn.tableCFMatrixView=function(param){return this.each(function(){table.call(this)});function table(){{var defaults={head:!0,left:1,'z-index':10};var settings=$.extend({},defaults,param);settings.table=this;settings.parent=$(settings.table).parent();setParent();if(settings.head==!0)
fixHead();if(settings.left>0)
fixLeft();setCorner();$(settings.parent).trigger("scroll");function setCorner(){var table=$(settings.table);if(settings.head){if(settings.left>0){var tr=table.find("thead tr");tr.each(function(k,row){solverLeftColspan(row,function(cell){$(cell).css("z-index",settings['z-index']+1)})})}}}
function setParent(){var parent=$(settings.parent);var table=$(settings.table);parent.append(table);if($(table).width()>$(table).parent().width()){parent.css({'overflow-x':'auto'})}
if($(table).height()>$(table).parent().height()){parent.css({'overflow-y':'auto'})}
parent.scroll(function(){var scrollWidth=parent[0].scrollWidth;var clientWidth=parent[0].clientWidth;var scrollHeight=parent[0].scrollHeight;var clientHeight=parent[0].clientHeight;var top=parent.scrollTop();var left=parent.scrollLeft();var bottom=scrollHeight-clientHeight-top;if(settings.head){if(top>1){this.find("thead tr > *").css("top",top-1)}else{this.find("thead tr > *").css("top",0)}}
if(settings.left>0){if(left>1){settings.leftColumns.css("left",left-1)}else{settings.leftColumns.css("left",0)}}}.bind(table))}
function fixHead(){var thead=$(settings.table).find("thead");var tr=thead.find("tr");var cells=thead.find("tr > *");cells.css({'position':'relative'})}
function fixLeft(){var table=$(settings.table);settings.leftColumns=$();var tr=table.find("tr");tr.each(function(k,row){solverLeftColspan(row,function(cell){settings.leftColumns=settings.leftColumns.add(cell)})});var column=settings.leftColumns;column.each(function(k,cell){var cell=$(cell);cell.css({'position':'relative'})})}
function solverLeftColspan(row,action){var fixColumn=settings.left;var inc=1;for(var i=1;i<=fixColumn;i=i+inc){var nth=inc>1?i-1:i;var cell=$(row).find("> *:nth-child("+nth+")");var colspan=cell.prop("colspan");if(cell.cellPos().left<fixColumn){action(cell)}
inc=colspan}}}}};function scanTable($table){var m=[];$table.children("tr").each(function(y,row){$(row).children("td, th").each(function(x,cell){var $cell=$(cell),cspan=$cell.attr("colspan")|0,rspan=$cell.attr("rowspan")|0,tx,ty;cspan=cspan?cspan:1;rspan=rspan?rspan:1;for(;m[y]&&m[y][x];++x);for(tx=x;tx<x+cspan;++tx){for(ty=y;ty<y+rspan;++ty){if(!m[ty]){m[ty]=[]}
m[ty][tx]=!0}}
var pos={top:y,left:x};$cell.data("cellPos",pos)})})};$.fn.cellPos=function(rescan){var $cell=this.first(),pos=$cell.data("cellPos");if(!pos||rescan){var $table=$cell.closest("table, thead, tbody, tfoot");scanTable($table)}
pos=$cell.data("cellPos");return pos}})