<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_AdvancedHidePrice
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php
$customOption = $block->getCustomOption();
$mediaPath = $block->getMediaPath();
?>
<?php if ($customOption) :?>
<tr>
    <td style="font-size:12px;padding:7px 9px 9px 9px;border:1px solid #EAEAEA;"><?php echo $block->escapeHtml(__('Custom Options:'))?></td>
    <td style="font-size:12px;padding:7px 9px 9px 9px;border:1px solid #EAEAEA;">
    <?php foreach ($customOption as $option):?>
    <p>
        <?php if ($option['option_type'] == 'file') : ?>
            <?php $url = $mediaPath.'callprice/'.$block->getProductId().'/'.$block->getCustomerEmail().'/'.$option['value']; ?>
        <?php echo $option['name'].': ' ?><a href="<?= $url; ?>"><?php echo $option['value'] ?></a>
        <?php else: ?>
        <?php echo $option['name'].': '.$option['value'] ?>
        <?php endif;?>
    </p>
    <?php endforeach;?>
    </td>
</tr>
<?php endIf; ?>
