<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Catalog\Block\Adminhtml\Category\AssignProducts $block */
/** @var \Magento\Catalog\Block\Adminhtml\Category\Tab\Product $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?php  echo $block->getGridHtml(); ?>
<input type="hidden" name="customers" id="in_reps" data-form-part="paymentmethod_paymentmethod_form" value=""/>
<script type="text/x-magento-init">
    {
    "*": {
    "FME_RestrictPaymentMethod/customers/assign-customers": {
    "selectedCustomers": <?= /* @escapeNotVerified */ $block->getCustomersJson() ?>,
    "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
    }
    }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
