<?php
/**
 * Copyright © Rob Aimes - https://aimes.dev
 * https://github.com/robaimes
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Aimes\VoiceSearch\ViewModel\Config $config */
/** @var \Aimes\VoiceSearch\ViewModel\StoreLocale $locale */
$config = $block->getData('config');
$locale = $block->getData('locale');
$title = $block->getData('title') ?: __('Voice Search');
?>

<button id="search-voice-input"
        class="action voice-input hidden"
        type="button" 
        title="<?= $block->escapeHtmlAttr($title) ?>"
        data-mage-init='{
            "Aimes_VoiceSearch/js/voice-search":{
                "storeLocale": "<?= /* @noEscape */ $locale->getConvertedLocaleCode() ?>",
                "skipSuggestions": <?= /* @noEscape */ (int) $config->getSkipSuggestions() ?>
            }
        }'>
    <span><?= $block->escapeHtml($title) ?></span>
    <i class="fa fa-microphone" style="font-size: 20px;opacity: 0.8;"></i>
</button>

<style>
    #search-voice-input {
        transition: none; /* Remove hover effects */
    }

    #search-voice-input:hover {
        /* Disable hover styles */
        background-color: unset;
        color: unset;
    }
</style>

