<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>

<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="top_header_container">
<div class="container_switcher" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    <!--strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Language') ?></span></strong-->
    <div class="actions dropdown options switcher-options">
       <div>
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php //if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <span class="cswitcher_custom">
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>' style="display: inline-block; background-position: 10% 50%; padding-left: 45px;background-repeat: no-repeat;background-image:url('<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/flags/flag_' . $block->escapeHtml($_lang->getCode()) . '.png') ?>');" >
                            <?php echo $block->escapeHtml($_lang->getName()) ?></a>
                    </span>
                <?php //endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<?php endif; ?>
<span class="callusbtn"><strong>CALL US (9-5)</strong> <span class="color-red">+962 777 635 777</span></span>
</div>