<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Improved Sorting for Magento 2
 */
/**
 * @var \Amasty\Sorting\Block\Widget\Featured $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<?php if (($_products = $block->getProductCollection()) && $_products->getSize()): ?>
    <div class="block widget amsorting block-featured-products-images">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $escaper->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?php $suffix = $block->getNameInLayout(); ?>
            <ol id="widget-featured-products-<?= $escaper->escapeHtml($suffix) ?>"
                class="product-items product-items-images">
                <?php foreach ($_products->getItems() as $_product): ?>
                    <li class="product-item">
                        <a class="product-item-photo"
                           href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                           title="<?= /* @noEscape  */ $block->stripTags($_product->getName(), null, true) ?>">
                            <?php $image = $block->getImageModel($_product) ?>
                            <span class="product-image-container">
                                <img src="<?= $escaper->escapeUrl($image->getUrl()) ?>"
                                     width="<?= $escaper->escapeHtmlAttr($image->getWidth()) ?>"
                                     height="<?= $escaper->escapeHtmlAttr($image->getHeight()) ?>"
                                     alt="<?= $escaper->escapeHtmlAttr($image->getLabel()) ?>"/>
                            </span>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ol>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>
