<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Improved Sorting for Magento 2
 */
/**
 * @var \Amasty\Sorting\Block\Widget\Featured $block
 * @var \Magento\Framework\Escaper $escaper
 */

use Magento\Catalog\Block\Product\ReviewRendererInterface;
?>

<?php if (($_products = $block->getProductCollection()) && $_products->getSize()): ?>
    <div class="block widget amsorting block-featured-products-list">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $escaper->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?php $suffix = $block->getNameInLayout(); ?>
            <?php $iterator = 1; ?>
            <ol class="product-items" id="widget-featured-products-<?= $escaper->escapeHtml($suffix) ?>">
                <?php foreach ($_products->getItems() as $_product): ?>
                    <?= /* @noEscape */ ($iterator++ == 1)
                        ? '<li class="product-item">'
                        : '</li><li class="product-item">' ?>
                    <div class="product-item-info">
                        <a class="product-item-photo"
                           href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                           title="<?= /* @noEscape */ $block->stripTags($_product->getName(), null, true) ?>">
                            <?php $image = $block->getImageModel($_product) ?>
                            <span class="product-image-container">
                                <img src="<?= $escaper->escapeUrl($image->getUrl()) ?>"
                                     width="<?= $escaper->escapeHtmlAttr($image->getWidth()) ?>"
                                     height="<?= $escaper->escapeHtmlAttr($image->getHeight()) ?>"
                                     alt="<?= $escaper->escapeHtmlAttr($image->getLabel()) ?>"/>
                            </span>
                        </a>
                        <div class="product-item-details">
                            <strong class="product-item-name">
                                <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                   title="<?= /* @noEscape */ $block->stripTags($_product->getName(), null, true) ?>)"
                                   class="product-item-link">
                                    <?= $escaper->escapeHtml($block->getProductName($_product)) ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, ReviewRendererInterface::SHORT_VIEW) ?>
                            <?= $block->getProductPriceHtml($_product, '-widget-featured-' . $suffix) ?>
                            <div class="product-item-actions">
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                            <?php $url = $block->getAddToCartUrl($_product); ?>
                                            <button type="button"
                                                    title="<?= $escaper->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary"
                                                    data-mage-init='{"redirectUrl":{
                                                        "url":"<?= $escaper->escapeHtml($url) ?>"
                                                    }}'>
                                                <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        <?php else: ?>
                                            <?php $postData = $block->getPostData($_product); ?>
                                            <button type="button"
                                                    title="<?= $escaper->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary"
                                                    data-post='<?= $escaper->escapeHtml($postData) ?>'>
                                                <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"
                                                 title="<?= $escaper->escapeHtml(__('Availability')) ?>">
                                                <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                                            </div>
                                        <?php else: ?>
                                            <div class="stock unavailable"
                                                 title="<?= $escaper->escapeHtml(__('Availability')) ?>">
                                                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?= ($iterator == count($_products->getItems())+1) ? '</li>' : '' ?>
                <?php endforeach; ?>
            </ol>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>
