<?php
/**
 * @var $block \Bss\RewardPoint\Block\Adminhtml\EarnReport\Chart
**/
?>
<div class="earn_report_chart">
    <h2 style="margin-left: 55%; padding:20px;">Points Earned by Events (%)</h2>
    <canvas id="myChart" style="max-width: 400px; max-height: 400px; margin-left: 50%"></canvas>
</div>

<script type="text/x-magento-init">
    {
        "#myChart": {
            "Bss_RewardPoint/js/earnreport": {
                "dataChart": <?= $block->getTotal() ?>
            }
        }
    }
    </script>
