<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Address\Edit $block */
/** @var \Magento\Customer\ViewModel\Address $viewModel */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Customer\ViewModel\Address\RegionProvider $regionProvider */
$viewModel = $block->getViewModel();
$regionProvider = $block->getRegionProvider();
?>
<?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
<?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
<?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
<?php $_country_id = $block->getAttributeData()->getFrontendLabel('country_id'); ?>
<?php $_street = $block->getAttributeData()->getFrontendLabel('street'); ?>
<?php $_city = $block->getAttributeData()->getFrontendLabel('city'); ?>
<?php $_region = $block->getAttributeData()->getFrontendLabel('region'); ?>
<?php $_selectRegion = 'Please select a region, state or province.'; ?>
<?php $_displayAll = $block->getConfig('general/region/display_all'); ?>

<?php $_vatidValidationClass = $viewModel->addressGetAttributeValidationClass('vat_id'); ?>
<?php $_cityValidationClass = $viewModel->addressGetAttributeValidationClass('city'); ?>
<?php $_postcodeValidationClass_value = $viewModel->addressGetAttributeValidationClass('postcode'); ?>
<?php $_postcodeValidationClass = $_postcodeValidationClass_value; ?>
<?php $_streetValidationClass = $viewModel->addressGetAttributeValidationClass('street'); ?>
<?php $_streetValidationClassNotRequired = $_streetValidationClass !== null ?
    trim(str_replace('required-entry', '', $_streetValidationClass)) : ''; ?>
<?php $_regionValidationClass = $viewModel->addressGetAttributeValidationClass('region'); ?>
<form class="form-address-edit"
      action="<?= /* @noEscape*/ $escaper->escapeUrl($block->getSaveUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= /* @noEscape*/ $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= /* @noEscape*/ $escaper->escapeHtml(__('Contact Information')) ?></span></legend><br>
        <?= /* @noEscape*/ $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= /* @noEscape*/ $escaper->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= /* @noEscape*/ $escaper->escapeUrl($block->getErrorUrl()) ?>">
        <?= /* @noEscape*/ $block->getNameBlockHtml() ?>

        <?php if ($_company->isEnabled()): ?>
            <?= /* @noEscape*/ $_company->setCompany($block->getAddress()->getCompany())->toHtml() ?>
        <?php endif ?>

        <?php if ($_telephone->isEnabled()): ?>
            <?= /* @noEscape*/ $_telephone->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
            <div id="smserror" name="smserror" generated="true" class="mage-error" style="margin-top: -15px;"></div>
        <?php endif ?>

        <?php if ($_fax->isEnabled()): ?>
            <?= /* @noEscape*/ $_fax->setFax($block->getAddress()->getFax())->toHtml() ?>
        <?php endif ?>

    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= /* @noEscape*/ $escaper->escapeHtml(__('Address')) ?></span></legend><br>
        <div class="field street required">
            <label for="street_1" class="label"><span><?= /* @noEscape*/ /* @noEscape */ $_street ?></span></label>
            <div class="control">
                <div class="field primary">
                    <label for="street_1" class="label">
                        <span>
                            <?= /* @noEscape*/ $escaper->escapeHtml(__('Street Address: Line %1', 1)) ?>
                        </span>
                    </label>
                </div>
                <input type="text"
                       name="street[0]"
                       value="<?= /* @noEscape*/ $escaper->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                       title="<?= /* @noEscape*/ /* @noEscape */ $_street ?>"
                       id="street_1"
                       class="input-text <?= /* @noEscape*/ $escaper->escapeHtmlAttr($_streetValidationClass) ?>"/>
                <div class="nested">
                    <?php for ($_i = 1, $_n = $viewModel->addressGetStreetLines(); $_i < $_n; $_i++): ?>
                        <div class="field additional">
                            <label class="label" for="street_<?= /* @noEscape*/ /* @noEscape */ $_i + 1 ?>">
                                <span><?= /* @noEscape*/ $escaper->escapeHtml(__('Street Address: Line %1', $_i + 1)) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[<?= /* @noEscape*/ /* @noEscape */ $_i ?>]"
                                       value="<?= /* @noEscape*/ $escaper->escapeHtmlAttr($block->getStreetLine($_i + 1)) ?>"
                                       title="<?= /* @noEscape*/ $escaper->escapeHtmlAttr(__('Street Address %1', $_i + 1)) ?>"
                                       id="street_<?= /* @noEscape*/ /* @noEscape */ $_i + 1 ?>"
                                       class="input-text
                                        <?= /* @noEscape*/ $escaper->escapeHtmlAttr($_streetValidationClassNotRequired) ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <?php if ($viewModel->addressIsVatAttributeVisible()): ?>
            <div class="field taxvat">
                <label class="label" for="vat_id">
                    <span><?= /* @noEscape*/ /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="vat_id"
                           value="<?= /* @noEscape*/ $escaper->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                           title="<?= /* @noEscape*/ /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                           class="input-text <?= /* @noEscape*/ $escaper->escapeHtmlAttr($_vatidValidationClass) ?>"
                           id="vat_id">
                </div>
            </div>
        <?php endif; ?>
        <div class="field country required">
            <label class="label" for="country">
                <span><?= /* @noEscape*/ /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span>
            </label>
            <div class="control">
                <?= /* @noEscape*/ $block->getCountryHtmlSelect() ?>
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region_id">
                <span><?= /* @noEscape*/ /* @noEscape */ $_region ?></span>
            </label>
            <div class="control">
                <select id="region_id" name="region_id"
                        title="<?= /* @noEscape*/ /* @noEscape */ $_region ?>"
                        class="validate-select region_id"
                        <?= /* @noEscape*/ /* @noEscape */ !$_displayAll ? ' disabled="disabled"' : '' ?>>
                    <option value=""><?= /* @noEscape*/ $escaper->escapeHtml(__($_selectRegion)) ?></option>
                </select>
                <input type="text"
                       id="region"
                       name="region"
                       value="<?= /* @noEscape*/ $escaper->escapeHtmlAttr($block->getRegion()) ?>"
                       title="<?= /* @noEscape*/ /* @noEscape */ $_region ?>"
                       class="input-text validate-not-number-first
                        <?= /* @noEscape*/ $escaper->escapeHtmlAttr($_regionValidationClass) ?>"
                        <?= /* @noEscape*/ !$_displayAll ? ' disabled="disabled"' : '' ?>/>
            </div>
        </div>
        <div class="field city required">
            <label class="label" for="city">
                <span><?= /* @noEscape*/ /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="city"
                       value="<?= /* @noEscape*/ $escaper->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                       title="<?= /* @noEscape*/ $escaper->escapeHtmlAttr(__('City')) ?>"
                       class="input-text <?= /* @noEscape*/ $escaper->escapeHtmlAttr($_cityValidationClass) ?>"
                       id="city">
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip">
                <span><?= /* @noEscape*/ /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="postcode"
                       value="<?= /* @noEscape*/ $escaper->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                       title="<?= /* @noEscape*/ /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                       id="zip"
                       class="input-text validate-zip-international
                        <?= /* @noEscape*/ $escaper->escapeHtmlAttr($_postcodeValidationClass) ?>">
                <div role="alert" class="message warning">
                    <span></span>
                </div>
                <?= /* @noEscape*/ /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'div.message.warning') ?>
            </div>
        </div>

        <?php if ($block->isDefaultBilling()): ?>
            <div class="message info">
                <span><?= /* @noEscape*/ $escaper->escapeHtml(__("It's a default billing address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultBilling()): ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox">
                <label class="label" for="primary_billing">
                    <span><?= /* @noEscape*/ $escaper->escapeHtml(__('Use as my default billing address')) ?></span>
                </label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_billing" value="1" />
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()): ?>
            <div class="message info">
                <span><?= /* @noEscape*/ $escaper->escapeHtml(__("It's a default shipping address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultShipping()): ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox">
                <label class="label" for="primary_shipping">
                    <span><?= /* @noEscape*/ $escaper->escapeHtml(__('Use as my default shipping address')) ?></span>
                </label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_shipping" value="1">
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action save primary"
                    data-action="save-address"
                    disabled="disabled"
                    title="<?= /* @noEscape*/ $escaper->escapeHtmlAttr(__('Save Address')) ?>">
                <span><?= /* @noEscape*/ $escaper->escapeHtml(__('Save Address')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= /* @noEscape*/ $escaper->escapeUrl($block->getBackUrl()) ?>">
                <span><?= /* @noEscape*/ $escaper->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape*/ /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes() ?>
            }
        },
        "#country": {
            "directoryRegionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape*/ /* @noEscape */ $_displayAll ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape*/ /* @noEscape */ $regionProvider->getRegionJson(); ?>,
                "defaultRegion": "<?= /* @noEscape*/ (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape*/ /* @noEscape */ $viewModel->dataGetCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php
define('BUILD_VERSION', '1.0.1');
define('DEBUG_MODE', false); // DEBUG
define('PHONE_INPUT_ELEMENT', 'input[name="telephone"]');
$mage_block= $block->getLayout()->createBlock('Magecomp\Whatsappcountryflag\Block\Intphoneinput');
?>
<?php if (DEBUG_MODE): ?>
        <pre>
                DetectByIp: <?= /* @noEscape*/ $mage_block->getDetectByIp(); ?>
        <br />
                CurrentIP: <?php print_r($mage_block->getCustomerIPDetails()); ?>
    </pre>
<?php endif; ?>
<script type="text/javascript">
    var int_phone_input_element = '<?= /* @noEscape*/ PHONE_INPUT_ELEMENT; ?>';
</script>
<script>
    require([
            'jquery',
            'Magecomp_Whatsappcountryflag/js/intlTelInput.min'
        ],
        function($) {
            function Smsresetdata()
            {
                jQuery(int_phone_input_element).removeClass('mage-error');
                jQuery('#smserror').html('');
            }

            function Smstoggeldata(Elementid)
            {
                jQuery(Elementid).toggle();
            }
            <?php if ($mage_block->isEnabled()): ?>
                var country_flag = "<?= /* @noEscape*/ $mage_block->getDefualtCountry();?>";
                <?php if ($mage_block->getDetectByIp()):?>
                    country_flag = "<?= /* @noEscape*/ $mage_block->getCustomerIPDetails();?>";
                <?php endif; ?>
                
                jQuery(int_phone_input_element).intlTelInput({
                    initialCountry: country_flag
                });
                jQuery(int_phone_input_element).removeAttr('placeholder');
              
                jQuery('#telephone').keyup(function(){
                    Smsresetdata();
                    var str = jQuery(".selected-flag").attr("title");
                    var countrycodeval =  str.split('+')[1];
                    var mobilelength=jQuery(int_phone_input_element).val().length;
                    var mobile = countrycodeval+jQuery(int_phone_input_element).val();
                    
                    jQuery("#countryreg").val(countrycodeval);
                    var temp = true;
                    if(mobile == null || mobile == '')
                    {
                        temp=false;
                        jQuery(int_phone_input_element).addClass('mage-error');
                        $('#smserror').html('<?= /* @noEscape*/ __('This is a required field.') ?>');
                    }
                    if(!$.isNumeric(mobile) || mobile.substring(0,1)=='+' || mobile.substring(0,1)=='-')
                    {
                         temp=false;
                        jQuery(int_phone_input_element).addClass('mage-error');
                        $('#smserror').html('<?= /* @noEscape*/ __('Make sure, you have entered valid WhatsApp Number.') ?>');
                    }
                    var countrycode = jQuery(".flag-container > .country-list > .active").attr("data-country-code");
                    $.ajax({
                        type: "POST",
                        url: '<?= /* @noEscape*/ $block->getUrl('whatsappcountryflag/customer/validatephone')?>',
                        data:{'mobile':mobile,'countrycode':countrycode,'mobilelength':mobilelength,'country_id':countrycodeval},
                        success: function(data)
                        {
                            if(data.validate==true){
                                $('#smserror').html('<?= /* @noEscape*/ __('') ?>');
                                jQuery('button.action.save.primary[data-action="save-address"]').prop("disabled", false);
                            }
                            else{
                                if(temp==true){
                                     $('#smserror').html(data.message);     
                                }
                                jQuery('button.action.save.primary[data-action="save-address"]').prop("disabled", true);
                            }
                        },
                        error: function(data) {
                            $('#smserror').html('<?= /* @noEscape*/ __('Something went wrong, Try again later.') ?>');
                        }
                    });
                });
                jQuery('.country-list li').click(function(){
                    jQuery(int_phone_input_element).val('');
                });
                jQuery(int_phone_input_element).blur(function(){
                    var str = jQuery(".selected-flag").attr("title");
                    var countrycodeval =  str.split('+')[1];
                        var mobile = jQuery(int_phone_input_element).val();
                        var strFirstThree = mobile.substring(0,countrycodeval.length);
                        if(mobile.indexOf(countrycodeval) != -1){
                                mobile.replace(countrycodeval,'');
                        }
                        if(countrycodeval!=strFirstThree){
                                 jQuery(int_phone_input_element).val(countrycodeval+mobile);
                        }
                    
                });
            <?php endif; ?>

    });
</script>