<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_ProductTags
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
/**
 *
 * @var  $block  Bss\ProductTags\Block\ProductTag\Sidebar
 */
?>
<?php $collection = $block->getCollection();
?>
<?php if ($collection): ?>
    <div class="block block-tag">
        <div class="block-title">
            <strong class="title"><?php echo __('POPULAR TAGS') ?></strong>
        </div>
        <div class="block-content">
            <?php foreach ($collection as $key => $value): ?>
                <?php $value['router_tag'] = (!empty($value['router_tag'])) ? $value['router_tag'] : 'catalogtags'; ?>
                <a title="<?php echo $value['tag_name']; ?>"
                   href="<?php echo $block->getUrl($value['router_tag']) . $value['tag_key']; ?>" >
                    <?php
                        if ($key != (count($collection) - 1)) {
                            echo $value['tag_name'] . ',';
                        } else {
                            echo rtrim($value['tag_name'], ',');
                        }
                    ?>
                </a>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
