<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomOptionAbsolutePriceQuantity
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile
?>
<?php /* @var $block \Bss\CustomOptionAbsolutePriceQuantity\Block\Options\Type\Select */ ?>
<?php $option = $block->getOption(); ?>
<div class="admin__field field<?php if ($option->getIsRequire()) echo ' required _required' ?>">
    <label class="label admin__field-label">
        <span><?php echo  $block->escapeHtml($option->getTitle()) ?></span>
        <?php  echo $block->getBssCustomOptionBlock('after_title'); ?>
    </label>
    <div class="control admin__field-control">
        <?php echo $block->getValuesHtml() ?>
        <?php if ($option->getIsRequire()): ?>
            <?php if ($option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_RADIO || $option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_CHECKBOX): ?>
                <span id="options-<?php /* @escapeNotVerified */ echo $option->getId() ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>
    </div>
</div>
<?php if ($option->getBssCoapQty()): ?>
<div class="field admin__field">
    <label class="label admin__field-label"><span><?php /* @escapeNotVerified */ echo $option->getTitle() . ' - ' . __('Options Qty') ?></span></label>
    <div class="control admin__field-control">
        <input
            id="product_composite_configure_input_qty" class="input-text admin__control-text qty"
            type="text" name="option_qty[<?php  echo $option->getId() ?>]"
            value="<?php echo $block->getProduct()->getData('bss_reorder_option_qty/'.$option->getId()) ?>" />
    </div>
</div>
<?php endif;?>
