<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomOptionAbsolutePriceQuantity
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile
?>
<?php /* @var $block \Bss\CustomOptionAbsolutePriceQuantity\Block\Options\Type\Text */ ?>
<?php $option = $block->getOption(); ?>
<div class="field admin__field<?php if ($option->getIsRequire()) echo ' required _required' ?>">
    <label class="admin__field-label label">
        <?php echo  $block->escapeHtml($option->getTitle()) ?>
        <?php if ($option->getPriceType() === "abs") : ?>
          <?php echo ' ' . __('(Absolute Price)'); ?>
        <?php endif; ?>
        <?php /* @escapeNotVerified */ echo $block->getFormatedPrice() ?>
    </label>
    <div class="control admin__field-control">
        <?php if ($option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_FIELD): ?>
            <input type="text" id="options_<?php /* @escapeNotVerified */ echo $option->getId() ?>_text" class="input-text admin__control-text <?php echo $option->getIsRequire() ? ' required-entry' : '' ?> <?php /* @escapeNotVerified */ echo $option->getMaxCharacters() ? ' validate-length maximum-length-' . $option->getMaxCharacters() : '' ?> product-custom-option" name="options[<?php /* @escapeNotVerified */ echo $option->getId() ?>]" value="<?php echo $block->escapeHtml($block->getDefaultValue()) ?>" price="<?php /* @escapeNotVerified */ echo $block->getCurrencyPrice($option->getPrice(true)) ?>" />
        <?php elseif ($option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_AREA): ?>
            <textarea id="options_<?php /* @escapeNotVerified */ echo $option->getId() ?>_text" class="admin__control-textarea <?php echo $option->getIsRequire() ? ' required-entry' : '' ?> <?php /* @escapeNotVerified */ echo $option->getMaxCharacters() ? ' validate-length maximum-length-' . $option->getMaxCharacters() : '' ?> product-custom-option" name="options[<?php /* @escapeNotVerified */ echo $option->getId() ?>]" rows="5" cols="25" price="<?php /* @escapeNotVerified */ echo $block->getCurrencyPrice($option->getPrice(true)) ?>"><?php echo $block->escapeHtml($block->getDefaultValue()) ?></textarea>
        <?php endif;?>

        <?php if ($option->getMaxCharacters()): ?>
            <p class="note"><?php /* @escapeNotVerified */ echo __('Maximum number of characters:')?> <strong><?php /* @escapeNotVerified */ echo $option->getMaxCharacters() ?></strong></p>
        <?php endif; ?>
    </div>
</div>
<?php if ($option->getBssCoapQty()): ?>
<div class="field admin__field">
    <label class="label admin__field-label"><span><?php /* @escapeNotVerified */ echo $option->getTitle() . ' - ' . __('Options Qty') ?></span></label>
    <div class="control admin__field-control">
        <input
            id="product_composite_configure_input_qty" class="input-text admin__control-text qty"
            type="text" name="option_qty[<?php  echo $option->getId() ?>]"
            value="<?php echo $block->getProduct()->getData('bss_reorder_option_qty/'.$option->getId()) ?>" />
    </div>
</div>
<?php endif;?>
