<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_GiftCard
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/** @var \Bss\GiftCard\Block\Wishlist\Configure\Updater $block */
?>
<div id="bss-gift-card-wishlist-configure"></div>
<script type="text/x-magento-init">
    {
        "#bss-gift-card-wishlist-configure": {
            "Bss_GiftCard/js/view/wishlist/configure": <?= /* @noEscape */ $block->getUpdaterData() ?>
        }
    }
</script>