<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_ConfigurableMatrixView
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

/** @var $block \Bss\ConfigurableMatrixView\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
	<div class="box-tocart">
		<div class="fieldset">
			<div class="actions">
				<button type="submit"
				title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
				class="action primary tocart"
				id="product-addtocart-button">
				<span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
			</button>
			<?php echo $block->getChildHtml('', true) ?>
		</div>
	</div>
</div>
<?php endif; ?>
<?php if ($block->isNewAddtocartTemplate()): ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Bss_ConfigurableMatrixView/js/validate-product": {}
            }
        }
    </script>
<?php else: ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Bss_ConfigurableMatrixView/js/validate-product": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
<?php endif; ?>
