<?php
$dataHelper    		   = $this->helper('\Magezon\LookBook\Helper\Data');
$mainColor     		   = $dataHelper->getMainColor();
$markerBgColor         = $dataHelper->getMarkerBackgroundColor();
$markerTitleColor      = $dataHelper->getMarkerTextColor();
$markerBorderColor     = $dataHelper->getMarkerBorderColor();
$markerWidth	       = $dataHelper->getMarkerWidth();
$markerHeight	       = $dataHelper->getMarkerHeight(); 
$productPageTitleColor = $dataHelper->getProductPageProfileTitleColor();
$productPageBtnColor   = $dataHelper->getProductPageProfileButtonColor();
?>
<style>
	<?php if ($mainColor) { ?>
		.lookbook-marker-type2 .lookbook-profile-products::-webkit-scrollbar-thumb,
		.lookbook-product:after,
		.lookbook-product:hover:after {
            background-color: <?= $mainColor ?>; 
        }
        .lookbook-body-wraper .profile-content .profile-title a:hover h3,
        .lookbook-profile-carousel .profile-item-inner .profile-item-title a:hover,
        .lookbook-marker-type2 .lookbook-btn-quick-view:hover,
		.lookbook-product:hover .lookbook-profile-title h3, 
		.lookbook-product.active .lookbook-profile-title h3 {
        	color: <?= $mainColor ?>;
        }
        .lookbook-profile-carousel .profile-item-inner .profile-item-title .btn-link,
        #lookbook-popup .lookbook-popup-loader .lookbook-popup-loader-bar {
        	background-color: <?= $mainColor ?>;
        }
	<?php } ?>
	<?php if ($markerBgColor || $markerTitleColor || $markerBorderColor || $markerWidth || $markerHeight) { ?>
		.lookbook-profile-marker > span {
			background: <?= $markerBgColor ?>;
			border-color: <?= $markerBorderColor ?>;
			width: <?= $markerWidth ?>px;
	        height: <?= $markerHeight ?>px;
		}
		.lookbook-profile-marker > span,
		.lookbook-profile-marker > span i {
			color: <?= $markerTitleColor ?>;
		}
		@keyframes lookbook-pulse {
		    0% {
		        transform: scale(.5);
		        box-shadow: 0px 1px 0px 3px transparent, 0px 0px 0px 0px <?= $markerBorderColor ?>;
		    }
		    30% {
		        box-shadow: 0px 1px 0px 3px transparent, 0px 0px 0px 5px <?= $markerBorderColor ?>;
		    }
		    70% {
		        box-shadow: 0px 1px 0px 3px transparent, 0px 0px 0px 15px <?= $markerBorderColor ?>;
		    }
		    100% {
		        transform: scale(1.0); 
		        box-shadow: 1px 1px 3px 1px transparent, 0px 0px 0px 30px transparent;
		    }
		}
	<?php } ?>

	<?php if ($productPageTitleColor) { ?>
		.lookbook-profile-carousel .profile-item-inner .profile-item-title h3 {
			color: <?= $productPageTitleColor ?>;
		}
	<?php } ?>

	<?php if ($productPageBtnColor) { ?>
		.lookbook-profile-carousel .profile-item-inner .profile-item-title .btn-link {
			background-color: <?= $productPageBtnColor ?>;
		}
	<?php } ?>
</style>
 