<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_Gallery
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

/**
 * Block
 *
 * @var $block \Bss\Gallery\Block\Adminhtml\Category\Edit\Tab\ListImageObject
 * @var $secureRenderer \Magento\Framework\View\Helper\SecureHtmlRenderer
 */
?>

<?php if(version_compare($block->magentoVersion(), '2.4.0', '>') ): ?>
    <?php
    /** @var \Magento\Framework\Json\Helper\Data $jsonHelper */
    $jsonHelper = $block->getData('jsonHelper');
    $dependencyJsObject = ($block->getDependencyJsObject() ? 'registry' : '');
    $encodedId = /* @noEscape */
        $jsonHelper->jsonEncode($block->getId());
    $scriptString = <<<script
    var deps = [];
    deps.push('mage/adminhtml/grid');
    require(deps, function(){
    //<![CDATA[
    {$block->escapeJs($block->getJsObjectName())} = new varienGrid({$encodedId},
         '{$block->escapeJs($block->getGridUrl())}',
         '{$block->escapeJs($block->getVarNamePage())}',
         '{$block->escapeJs($block->getVarNameSort())}',
         '{$block->escapeJs($block->getVarNameDir())}',
         '{$block->escapeJs($block->getVarNameFilter())}'
         );
    {$block->escapeJs($block->getJsObjectName())}.useAjax = '1';
    {$block->escapeJs($block->getJsObjectName())}.rowClickCallback = openGridRow;
    //]]>
});
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php else: ?>
    <script>
        var deps = [];

        deps.push('mage/adminhtml/grid');

        require(deps, function(<?= ($block->getDependencyJsObject() ? 'registry' : '') ?>){
            <?php //TODO: getJsObjectName and getRowClickCallback has unexpected behavior. Should be removed ?>

            <?php if ($block->getDependencyJsObject()) : ?>
            registry.get('<?= $block->escapeJs($block->getDependencyJsObject()) ?>', function (<?= $block->escapeJs($block->getDependencyJsObject()) ?>) {
                <?php endif; ?>

                <?= $block->escapeJs($block->getJsObjectName()) ?> = new varienGrid('<?= $block->escapeHtml($block->getId()) ?>', '<?= $block->escapeJs($block->getGridUrl()) ?>', '<?= $block->escapeJs($block->getVarNamePage()) ?>', '<?= $block->escapeJs($block->getVarNameSort()) ?>', '<?= $block->escapeJs($block->getVarNameDir()) ?>', '<?= $block->escapeJs($block->getVarNameFilter()) ?>');
                <?= $block->escapeJs($block->getJsObjectName()) ?>.useAjax = <?= /* @noEscape */ $block->getUseAjax() ? 'true' : 'false' ?>;
                <?php if ($block->getRowClickCallback()) : ?>
                <?= $block->escapeJs($block->getJsObjectName()) ?>.rowClickCallback = <?= /* @noEscape */ $block->getRowClickCallback() ?>;
                <?php endif; ?>
                <?php if ($block->getCheckboxCheckCallback()) : ?>
                <?= $block->escapeJs($block->getJsObjectName()) ?>.checkboxCheckCallback = <?= /* @noEscape */ $block->getCheckboxCheckCallback() ?>;
                <?php endif; ?>
                <?php if ($block->getSortableUpdateCallback()) : ?>
                <?= $block->escapeJs($block->getJsObjectName()) ?>.sortableUpdateCallback = <?= /* @noEscape */ $block->getSortableUpdateCallback() ?>;
                <?php endif; ?>
                <?= $block->escapeJs($block->getJsObjectName()) ?>.bindSortable();
                <?php if ($block->getRowInitCallback()) : ?>
                <?= $block->escapeJs($block->getJsObjectName()) ?>.initRowCallback = <?= /* @noEscape */ $block->getRowInitCallback() ?>;
                <?= $block->escapeJs($block->getJsObjectName()) ?>.initGridRows();
                <?php endif; ?>
                <?php if ($block->getChildBlock('grid.massaction') && $block->getChildBlock('grid.massaction')->isAvailable()) : ?>
                <?= /* @noEscape */ $block->getChildBlock('grid.massaction')->getJavaScript() ?>
                <?php endif ?>
                <?= /* @noEscape */ $block->getAdditionalJavaScript() ?>

                <?php if ($block->getDependencyJsObject()) : ?>
            });
            <?php endif; ?>
        });
    </script>
<?php endif; ?>
