<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_Gallery
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

/**
 * Block
 *
 * @var $block \Bss\Gallery\Block\Adminhtml\Category\Edit\Tab\Image
 */
$session = $block->createObj();
$keySession = $block->getKeySession();
$url = $block->createUrl();
$ajaxUrl = $url->getUrl('/category/thumb') . 'keys/' . $keySession;
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Bss_Gallery/js/tab_image": {
                "urls" : "<?= $block->escapeHtml($ajaxUrl) ?>",
                "sessions" : "<?= $block->escapeHtml($session->getKeySession()) ?>",
                "itemtThumbId" : "<?= $block->escapeHtml($block->getItemThumbId()) ?>"
            }
        }
    }

</script>
